### PR TITLE
feat: Add `onReleased` action to `AdvancedButtonComponent` which will be called within `onTapUp`

### LINKED ISSUE #3150: `AdvancedButtonComponent` doesn't show `downSkin` when changing the route
### What could be improved

`AdvancedButtonComponent` doesn't show the `downSkin` if the action of `onPressed` changes the router to another page. That is because the router is changed before the `downSkin` is showen as the `onPressed` action is called in `onTapDown` instead of `onTapUp`.

My suggestion is to move calling `onPressed` action to `onTapUp` method instead of `onTapDown`.

### Why should this be improved

That makes the `AdvancedButtonComponent` more natural and similar to many other platforms. That also allows users to skip the action if they move the mouse pointer or their finger outside the button box.

### Risks

The current behavior of the `AdvancedButtonComponent` will slightly get changed, as the action will be called on tap up. With normal click/press, that should not be noticable.

### More information

_No response_

### Other

- [X] Are you interested in working on a PR for this?

### PR DESCRIPTION
**Pull request by mabdelaal86**
# Description

Add `onReleased` action which will be called within `onTapUp`. That fixed some scenarios which require the pressed action to be called after the user taps up the button.

For example, `AdvancedButtonComponent` doesn't show the `downSkin` if the action of `onPressed` changes the router to another page. That is because the router is changed before the `downSkin` is shown as the `onPressed` action is called in `onTapDown`.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Fixes #3150

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by mabdelaal86** [comment]
The failed test case seems unrelated to my changes and all tests are passed locally with `melos run test`!
Is there a way to rerun the checks again?

**Comment by spydon** [comment]
I don't think this is worth a breaking change, it's better to expose a callback for onTapUp. In UI's buttons often trigger in onTapUp, but in games, when mashing a fire button for example, you usually want onTapDown.

**Comment by mabdelaal86** [comment]
Yeah, that makes sense. I didn't think about it, since I'm developing mainly board games, which are kind of UI apps.

**Comment by mabdelaal86** [comment]
Does it worth adding a callback to the `AdvancedBottonComponent` for onTapUp? or just implement a custom version in my game?

**Comment by spydon** [comment]
> Does it worth adding a callback to the `AdvancedBottonComponent` for onTapUp? or just implement a custom version in my game?

I think it would be worth adding! I guess we should add `onTapDown` then too and deprecate `onPressed` in the long run.

**Comment by mabdelaal86** [comment]
I have added `onReleased` event which will be called from `onTapUp`.

**Comment by spydon** [comment]
> I have added `onReleased` event which will be called from `onTapUp`.

Sounds good! Then we can refactor it to `onTapDown` and `onTapUp` for V2 instead (in a distant future)

**Review by spydon — APPROVED** [review]
Lgtm, thanks for your contribution!

**Comment by mabdelaal86** [comment]
Thanks a lot for the fast review

**Pull request merged**
