### PR TITLE
Removing unused deps

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Removing unused dependencies on Flame.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] I have formatted my code with `flutter format`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Review by luanpotter — APPROVED** [review]
Nice!

**Review by luanpotter — CHANGES_REQUESTED** [review]
Actually, run `flutter pub get`, it should change the lock file.

**Comment by erickzanardo** [comment]
> Actually, run `flutter pub get`, it should change the lock file.

I have, no changes happened, I found it weird too.

**Comment by luanpotter** [comment]
Really? weird that a lock file is not under version control... but I guess dart uses weird "global" dependency versions so probably makes sense.

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by erickzanardo** [comment]
> Really? weird that a lock file is not under version control... but I guess dart uses weird "global" dependency versions so probably makes sense.

This is a good read about that (this is not pub but I think the reasoning is the same): https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

Go on the `Libraries vs Applications` section, (sorry there is no anchor on that article)

**Pull request merged**
