### PR TITLE
fix: flame_tiled - add centered anchor point for tile rotation

### PR DESCRIPTION
**Pull request by nathanaelneveux**
# Description

Added a centered anchor point to SpriteBatch creation so that rotations won't move tiles into the wrong position.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

I'm assuming this fixes the errant behavior described at the top of the project readme? There wasn't a lot of detail. With this patch rotations work in my project.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
Some tests are failing, due to the update. It looks like the code change is sound, but that the tests need to be updated.

**Comment by nathanaelneveux** [comment]
I guess the only other question I have is whether this solves the issue described at the top of the README for this package and if I should remove that note with this PR?

Changing:
> :warning: Under the current sprite batch implementation, Flips are not working properly. 
> Any help is appreciated looking into this issue.
> 
> You might also experience extra lines while rendering due to a bug in Flutter,
> see [this issue](https://github.com/flame-engine/flame/issues/1152).

to something like:
> :warning: Under the current sprite batch implementation you might experience extra
> lines while rendering due to a bug in Flutter,
> see [this issue](https://github.com/flame-engine/flame/issues/1152).

**Review by wolfenrain — APPROVED** [review]

**Comment by spydon** [comment]
> I guess the only other question I have is whether this solves the issue described at the top of the README for this package and if I should remove that note with this PR?
> 
> Changing:
> 
> > warning Under the current sprite batch implementation, Flips are not working properly.
> > Any help is appreciated looking into this issue.
> > You might also experience extra lines while rendering due to a bug in Flutter,
> > see [this issue](https://github.com/flame-engine/flame/issues/1152).
> 
> to something like:
> 
> > warning Under the current sprite batch implementation you might experience extra
> > lines while rendering due to a bug in Flutter, see [this issue](https://github.com/flame-engine/flame/issues/1152).

Have you tried whether flips work? If they do agree the readme change sounds good.

**Comment by nathanaelneveux** [comment]
> Have you tried whether flips work? If they do agree the readme change sounds good.

It doesn't fix flips - just rotations. I had a map with random flips and rotations - the rotations stuck out as broken because they were drawn in the wrong location. I assumed that flips were broken similarly but a quick test with just flipped tiles shows that is a different problem.

**Comment by spydon** [comment]
Good to know, then we'll merge this and see if someone fixes flips in the future

**Pull request merged**
