### PR TITLE
Adding HoverDetector

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Adds "out of the box" support for mouse hover events.

hover

UPDATE:
move2

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
- [x] I have added examples for new features in `doc/examples`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm, would be great to have an example with the hoverdetector on the component too :)

**Review by renancaraujo — APPROVED** [review]

**Comment by hastebrot** [comment]
Maybe `onHover` can be renamed to `onPointerHover` to align it more with event name `PointerHoverEvent`. I'm working on a pull request to add a `ScrollDetector` with `onScroll()` callback that uses `PointerScrollEvent`.

**Comment by erickzanardo** [comment]
> Maybe `onHover` can be renamed to `onPointerHover` to align it more with event name `PointerHoverEvent`. I'm working on a pull request to add a `ScrollDetector` with `onScroll()` callback that uses `PointerScrollEvent`.

Thanks for the suggestion, we have been talking internally, and we decided to change the HoverDetector to MouseMovementDetector. I like your suggestion so I will rename it also to PointMovimentDetector.

Thanks for the scroll detector as well, hopefully I will be able to adjust this PR of mine tonight

**Review by spydon — APPROVED** [review]
Lgtm, much less confusing after the name change imho.

**Review by luanpotter — APPROVED** [review]
Nice! I am surprised we didnt have this yet, this is super useful

**Pull request merged**
