### PR TITLE
chore: Update audioplayers to ^6.0.0 in flame_audio

### LINKED ISSUE #3151: Update `flame_audio` to support `audioplayers:^6.0.0`
### What could be improved

`package:audioplayers` had a [`6.0.0` release](https://pub.dev/packages/audioplayers/changelog#600) with lots of fixes and some breaking changes, but `flame_audio` has a `^5.0.0` constraint.

### Why should this be improved

So users of `flame_audio` can benefit from the latest fixes and changes in `audioplayers` :)

### Risks

Likely best to not support both major versions, so downstream users who depend on `audioplayers:^5.0.0` might have to complete a few migrations to update to the updated `flame_audio` release.

### More information

_No response_

### Other

- [ ] Are you interested in working on a PR for this?

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description

This PR updates the audioplayers version for flame_audio.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #3151 and #3157 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by spydon** [comment]
I thought there were some breaking changes we had to adhere to, but seemingly not? 🤔

**Comment by ufrshubham** [comment]
> I thought there were some breaking changes we had to adhere to, but seemingly not? 🤔

I didn't notice any breaking change in flame_audio, but I am getting some conflicts with multiple definitions of the `Split` class.

**Comment by spydon** [comment]
> > I thought there were some breaking changes we had to adhere to, but seemingly not? 🤔
> 
> I didn't notice any breaking change in flame_audio, but I am getting some conflicts with multiple definitions of the `Split` class.

Aaah right, that is due to the devtools extension, I'll migrate that when I get home from Google I/O (the name changed in the new version).

**Review by spydon — APPROVED** [review]

**Review by renancaraujo — APPROVED** [review]

**Comment by ufrshubham** [comment]
> Aaah right, that is due to the devtools extension, I'll migrate that when I get home from Google I/O (the name changed in the new version).

Okay, I'll leave it up to you then. I tried hiding the other definition but now it fails analyze saying `Split` is not exported.

**Review by spydon — COMMENTED** [review]
The Dart SDK bump should probably preferably be done in a separate PR

**Comment by ufrshubham** [comment]
Okay, I'll move that change into a separate PR tomorrow

**Comment by ufrshubham** [comment]
Moved the dart sdk bump to #3160

**Review by luanpotter — APPROVED** [review]
LGTM

**Pull request merged**
