### PR TITLE
Unify all lint rules to be consistent across packages

### PR DESCRIPTION
**Pull request by luanpotter**
# Description

Unify all lint rules to be consistent across packages 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

## Related Issues
https://github.com/flame-engine/flame/issues/991

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Comment by luanpotter** [comment]
Found some context here: https://github.com/flutter/flutter/issues/40808

**Comment by spydon** [comment]
Seems like it will take a long time for all these classes that should be mixins in flutter to become mixins so I think we can close this and open this once they are done with that work.
The title of the PR is already solved by `flame_lint`.

**Comment by st-pasha** [comment]
I feel like, in general, we are substantially over-using the mixin pattern. In many cases when we declare something as a mixin, it would have better been a component instead.

**Comment by spydon** [comment]
> I feel like, in general, we are substantially over-using the mixin pattern. In many cases when we declare something as a mixin, it would have better been a component instead.

Do you have any examples?

**Comment by st-pasha** [comment]
> Do you have any examples?

Yes: `Tappable` is a mixin, but could just as easily be a component. Similarly for other event handlers. The advantage of components over mixins is that the mixins are "baked-in", whereas components can be easily added/removed at runtime.

**Comment by spydon** [comment]
> Yes: `Tappable` is a mixin, but could just as easily be a component. Similarly for other event handlers. The advantage of components over mixins is that the mixins are "baked-in", whereas components can be easily added/removed at runtime.

I can see the benefit of that, but then you can't handle the specific gesture logic on your component, you'll have to create another component that you then add to the component where you want this logic. It feels like it becomes unnecessarily nested.

**Comment by st-pasha** [comment]
What if there is a predefined component that takes a callback as an argument: `Tappable(TapCallback onTap)`.
Then, inside your component you can say `add(Tappable(this.handleTap1))`. Though this seems a bit more code than merely adding a mixin and defining `onTap()` method, but the advantage is that the callback can be changed at runtime or even removed at all.

Ok, i'm not actually sure how big of an advantage this is.

**Comment by luanpotter** [comment]
@spydon actually I don't agree this is solved; the rule is still commented out on Flame Lint:

https://github.com/flame-engine/flame/blob/main/packages/flame_lint/lib/analysis_options.yaml#L94

I'm not saying we need to wait years until Flutter decides to fix itself; rather, given the current context we should decide right now if we want this rule or not (seems to me the answer is not). And then, regardless of the decision, either have the rule or not on the file, and not having it commented out.

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/flame-engine/flame/pull/1117

**Pull request closed without merging**
