### PR TITLE
docs: Fix positioning of git commit message exclusion blocks in the PR template

### PR DESCRIPTION
**Pull request by luanpotter**
# Description

Fix positioning of git commit message exclusion blocks in the PR template. I found it a bit confusing as I think what we want to encourage is that the migration instructions go into the git message, but rn there is just a "Replace or remove this text." lost after the related issues. I don't think we want to include related issues? So it seems just out of order.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Maybe we should have and explanation of what should go inbetween those tags instead, before the start of the tag? So many people forget to remove the "Replace or remove" text.

**Comment by luanpotter** [comment]
This is the explanation, no?

> If the PR is breaking, uncomment this header and add instructions for how to migrate from the
currently released version to the new proposed way.

Or you mean replace `Replace or remove` with that message?

**Comment by spydon** [comment]
@luanpotter I mean something like this:
```md
Add the migration instruction in-between the two following tags:
<!-- End of exclude from commit message -->
<!-- Exclude from commit message -->
```

**Comment by luanpotter** [comment]
Fixed

**Review by spydon — APPROVED** [review]

**Pull request merged**
