### PR TITLE
docs: Revert auto expand flame section on documentation home page

### PR DESCRIPTION
**Pull request by spydon**
# Description

Reverts #1823, since the menu disappeared after it was merged.
@immadisairaj do you want to have a look at the site before I revert it to the previous state?

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

**Comment by spydon** [comment]
@immadisairaj doesn't seem like it was your PR that broke the menu

**Comment by immadisairaj** [comment]
Ohh.. Even I faced this issue. I thought I haven't built the docs site properly in local. I removed the changes I did in local, it was still the same. So, i am not sure of what happened.

I will try to see if i can find out anything once I am in front of PC.

**Comment by spydon** [comment]
> Ohh.. Even I faced this issue. I thought I haven't built the docs site properly in local. I removed the changes I did in local, it was still the same. So, i am not sure of what happened.
> 
> I will try to see if i can find out anything once I am in front of PC.

I think it was #1817, Pasha is also having a look. After that is solved I'll revert the revert of your PR. :smile:

**Comment by immadisairaj** [comment]
😅 Yeah, was checking commits and saw other commits that has changed for docs.

> revert the revert
Feels nice.. 😂

**Pull request merged**
