### PR TITLE
feat: `Component.childrenFactory` can be used to set up a global `ComponentSet` factory

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

Currently, the only way to override creation of a `ComponentSet` in a component is to create a derived class and override method `createComponentSet` within that class. However, this may not be always feasible, since Flame has many components that the user may want to use as-is.

In this PR I am adding an alternative approach: static global factory function `Component.childrenFactory`. Replacing this method with a custom implementation will make all subsequently created components use that custom factory function. The original `createComponentSet` function remains, both for backward-compatibility, and to make it possible to override creation of a component set within a particular subclass.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `flutter format` and the `flutter analyze` does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm, can you explain a bit about the usecase that you want to use it for, because I guess you have something in mind?

For the next release we are going to use Melos hopefully, so can you name your PR in a conventional commit way and skip the changelog entry? I'm going to update the guide today.

conventionalcommits.org/

**Comment by st-pasha** [comment]
Use case, for example: create all `ComponentSet`s in non-strict mode; or use custom implementation of a `ComponentSet` everywhere.

Not sure what you mean by "name your PR in a conventional commit", but I can remove the changelog entry.

**Comment by spydon** [comment]
> Not sure what you mean by "name your PR in a conventional commit", but I can remove the changelog entry.

Since we squash the commits, the name of the final commit will be the title of the PR, so the title should be a conventional commit name. You could basically just add `feat: ` in front of your current title.

**Comment by spydon** [comment]
@st-pasha I'll break out the analyze fixes to a new PR so that the feature isn't hidden within all that noise.

**Review by erickzanardo — COMMENTED** [review]
Can we add a small test for this new feature?

**Pull request merged**
