### PR TITLE
feat: Add broadphase generics to CollisionDetection

### PR DESCRIPTION
**Pull request by spydon**
# Description

This adds generics for the broadphase used in the collision detection.
This should simplify things a bit in #1894.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
@ASGAlex

**Comment by ASGAlex** [comment]
Since we're talking about breaking changes... 

To be honest, all these generics in collision detection system looks overcomplicated. The `<T extends Hitbox<T>>` is specified everywhere, but in real practice only the `ShapeHitbox` makes sense. Why should't we to use this base class instead generic type? If to specify `ShapeHitbox` explicitly in the `Broadphase` and `CollisionDetection` classes, then we will not need to pass these generics everywhere. And it would allow to avoid unnecesary type conversions at many places. 

As I can see, there are no hitboxes at the Flame which are not extended from ShapeHitbox. I also tried to replace all generics with basic types - ShapeHitbox and Broadphase - and everithing works well, at least in examples.

**Comment by spydon** [comment]
> Since we're talking about breaking changes...
> 
> To be honest, all these generics in collision detection system looks overcomplicated. The `<T extends Hitbox<T>>` is specified everywhere, but in real practice only the `ShapeHitbox` makes sense. Why should't we to use this base class instead generic type? If to specify `ShapeHitbox` explicitly in the `Broadphase` and `CollisionDetection` classes, then we will not need to pass these generics everywhere. And it would allow to avoid unnecesary type conversions at many places.
> 
> As I can see, there are no hitboxes at the Flame which are not extended from ShapeHitbox. I also tried to replace all generics with basic types - ShapeHitbox and Broadphase - and everithing works well, at least in examples.

This is because the collision detection system is fairly new, if we would only be able to use `ShapeHitbox` then the system is narrowed down to only be able to be used within FCS, if someone would want to have collision detection in for example Oxygen they can't have their hitboxes extend from `ShapeHitbox`. But there are changes coming to that in the future, where we'll use pure shapes as hitboxes instead of components, but right now since we need to know about the absolute transforms we have to go this route.

**Comment by ASGAlex** [comment]
>But there are changes coming to that in the future

Nice! Hope someday it will be reworked because with adding more dependencies we aggravates this "hell of generics" :-) 

As about this PR - i merged it into my branch, changes really helps to make life easier for end-user. Some previous type conversions become unnecesary. So I strongly confirm this PR usefulness 👍🏻

**Review by erickzanardo — APPROVED** [review]

**Pull request merged**
