### PR TITLE
Function to load all images in prefixed path

### PR DESCRIPTION
**Pull request by spydon**
# Description

To simplify loading all image assets in the specified (or default) path into the cache.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database]. Indicate, which of these issues are resolved or fixed by this PR.*

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Review by st-pasha — COMMENTED** [review]
From the API standpoint, there are now the following methods:
```
Images.load(String filename)
Images.loadAll(List<String> filenames)
Images.loadAllImages()
Images.loadAllFromPattern(Pattern pattern)
```
This is somewhat confusing, in particular, the 2nd and the 3rd methods sound too similar, and it's not immediately clear from their names what the difference is. So, perhaps we could go with something like
```
Images.load(String filename)
Images.loadList(List<String> filenames)
Images.loadAllAssets(Pattern? pattern)
```

**Review by erickzanardo — APPROVED** [review]

**Comment by spydon** [comment]
> From the API standpoint, there are now the following methods:
> 
> ```
> Images.load(String filename)
> Images.loadAll(List<String> filenames)
> Images.loadAllImages()
> Images.loadAllFromPattern(Pattern pattern)
> ```
> 
> This is somewhat confusing, in particular, the 2nd and the 3rd methods sound too similar, and it's not immediately clear from their names what the difference is. So, perhaps we could go with something like
> 
> ```
> Images.load(String filename)
> Images.loadList(List<String> filenames)
> Images.loadAllAssets(Pattern? pattern)
> ```

These are only for images though, not for all assets (like audio for example).

We do have the `loadAll` pattern for passing in a list in different places in the API too.
What about:
```
> Images.load(String filename)
> Images.loadAll()
> Images.loadList(List<String> filenames)
> Images.loadAllAssets(Pattern? pattern)

**Comment by spydon** [comment]
@st-pasha I can't come up with any better names, do you have any other suggestions by chance?
I'd like to keep the `loadAll` for the list, since that pattern is used both in dart and in other places in Flame.
And I think it is clearer for the user to have the method that loads from a pattern and the one that loads all images separate, instead of relying on a nullable argument. Any ideas from @flame-engine/flame-colab maybe?

**Comment by erickzanardo** [comment]
> @st-pasha I can't come up with any better names, do you have any other suggestions by chance?
> I'd like to keep the `loadAll` for the list, since that pattern is used both in dart and in other places in Flame.
> And I think it is clearer for the user to have the method that loads from a pattern and the one that loads all images separate, instead of relying on a nullable argument. Any ideas from @flame-engine/flame-colab maybe?

I am ok the current choice of names, can't think on better options too.

**Pull request merged**
