### PR TITLE
Rename Hitbox mixin to HasHitboxes

### PR DESCRIPTION
**Pull request by spydon**
# Description

Since you add hitboxes to a component that has the `Hitbox` mixin, it is a weird name for that mixin.
So therefore I'm renaming it to `HasHitboxes` instead, which is in line with many of our other mixins too.l

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

**Comment by st-pasha** [comment]
Why `HasHitboxes` and not `HasHitbox`? Can there be more than one hitbox on a Component?

**Comment by erickzanardo** [comment]
> Why `HasHitboxes` and not `HasHitbox`? Can there be more than one hitbox on a Component?

Yes, there can be more than one

**Comment by st-pasha** [comment]
Are they conceptually different hitboxes, like one hitbox for colliding with bullets and another for colliding with walls? Or is it more like a single conceptual hitbox but comprised of several physical shapes?

**Comment by spydon** [comment]
> Are they conceptually different hitboxes, like one hitbox for colliding with bullets and another for colliding with walls? Or is it more like a single conceptual hitbox but comprised of several physical shapes?

It can do both, since you can react to `onCollision` both in the component and directly in each separate hitbox.

**Review by wolfenrain — APPROVED** [review]

**Pull request merged**
