### PR TITLE
Move fps to mixin

### PR DESCRIPTION
**Pull request by wolfenrain**
# Description

Moved the FPS code to its own mixin so people can use it with the `Game` class instead of having to extend from `BaseGame` when they dont use components.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [ ] I have made corresponding changes to the documentation
- [ ] I have added examples for new features in `doc/examples`
- [ ] The continuous integration (CI) is passing

### CODE REVIEW

**Comment by wolfenrain** [comment]
> Nice! Maybe add a line in the docs about it?

Wasn't entirely sure where to add it. So if you have a suggestion, please tell! :+1:

**Comment by spydon** [comment]
> > Nice! Maybe add a line in the docs about it?
> 
> Wasn't entirely sure where to add it. So if you have a suggestion, do tell! :+1: 

In doc/debug.md I think it would fit nicely.

**Comment by luanpotter** [comment]
I love this! One thing that crossed my mind is: what if instead of having a boolean to control whether recordDt or not we use the presence of the mixin? And then neither BaseGame nor Game extends the mixin by default but you can enable it by adding the mixing to your Game (or BaseGame)? I don't have a strong opinion either way, and I am ok with merging this as is, but this thought crossed my mind and I wanted to float it. Might lead to a simpler API but might be harder to understand and maybe harder to toggle, not sure.

**Comment by wolfenrain** [comment]
> I love this! One thing that crossed my mind is: what if instead of having a boolean to control whether recordDt or not we use the presence of the mixin? And then neither BaseGame nor Game extends the mixin by default but you can enable it by adding the mixing to your Game (or BaseGame)? I don't have a strong opinion either way, and I am ok with merging this as is, but this thought crossed my mind and I wanted to float it. Might lead to a simpler API but might be harder to understand and maybe harder to toggle, not sure.

It would be a breaking changes in that case. Because currently only `BaseGame` has it implemented and people have to overwrite the `recordFps` functionality. If we base it on the presence of the mixin it would break backwards-compatibility.

But I do think it would be cleaner, so maybe for v1?

**Comment by wolfenrain** [comment]
> > > Nice! Maybe add a line in the docs about it?
> > 
> > 
> > Wasn't entirely sure where to add it. So if you have a suggestion, do tell! +1
> 
> In doc/debug.md I think it would fit nicely.

Updated the `doc/debug.md` and slightly restructured it, to seperate the non `BaseGame` debug features from the `BaseGame`. If you have any objections or see it differently do tell :-)

**Comment by wolfenrain** [comment]
> Hope I am not too late for a review, but I would like to suggest renaming the min to `FPSCounter`, What do you think?
> 
> Other than that, LGTM!

I personally dont mind, it is just a naming thing :-). Shall I supply a PR to change the name?

**Pull request merged**
