### PR TITLE
feat: Make ContactCallback begin end methods optional overrides

### LINKED ISSUE #1414: Make ContactCallback being and end method optional overrides
# What could be improved
Make `begin` and `end` methods optionally overridable when extending  `ContactCallback`, 

# Why should this be improved
Extending `ContactCallback` forces the developer to define both a `begin` and `end` method. This is convenient since a developer can use the IDE to automatically feel unimplemented methods. 

However, it is inconvenient when you only wish to implement one of `begin`, `end`, `preSolve` or `postSolve`. Since it not only pollutes the code with not very useful lines like the one below but also forces the developer to write a test ensuring that this method does nothing if they wish to strive for 100% coverage.

```dart
@override
void end(Foo _, Boo__, Contact ___) {}
```

# Any risks?
No

# More information

I'm interested in working on a PR for this. I've already raised a PR. If you're against the PR either because you believe is breaking or disagree with this change feel free to comment below and close the PR if this issue is not relevant. I'm not emotionally attached to the code so don't hesitate to refuse it :)!

### PR DESCRIPTION
**Pull request by alestiago**
# Description

Make begin and end methods optionally overridable when extending ContactCallback.

Also updates examples that were implementing empty methods.

## Checklist

- [X] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [X] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [X] I have updated/added tests for ALL new/updated/fixed functionality.
- [X] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [X] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

## Related Issues

Aims to resolve #1414.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]
LGTM!

**Review by spydon — APPROVED** [review]
Lgtm!

**Comment by spydon** [comment]
Anything in the docs that need to be updated regarding this?

**Comment by alestiago** [comment]
@spydon not really. There is an instance of:

``` 
@override
 void end(Ball ball, Wall wall, Contact contact) {}
```

Within the [`forge2d.md`](https://github.com/flame-engine/flame/blob/main/doc/other_modules/forge2d.md) but perhaps it's nice to keep it there for reference since later on the documentation adds:

> Every time `Ball` and `Wall` gets in contact `begin` will be called, and once the objects stop being in contact `end` will be called.

I think we can keep this documentation as it is since this change doesn't remove the sense from the doc. Perhaps, another PR could be raised to improve this and include information about pre and post solve methods too.

**Pull request merged**
