### PR TITLE
feat: adding svg example

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Adds an example for `flame_svg` on our examples collection.

This example will be used in a future PR to test the svg perfomance.

https://user-images.githubusercontent.com/835641/152365182-ac612af8-94ea-49ae-b42f-193f9c12aa1a.mov

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the
relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change. (Indicate it in the [Conventional Commit] prefix with a `!`,
  e.g. `feat!:`, `fix!:`).
- [x] No, this is *not* a breaking change.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database].
Indicate which of these issues are resolved or fixed by this PR, i.e. Fixes #xxxx*

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm! This might not pass the analyzer though since we don't have the melos action in here yet.

**Comment by erickzanardo** [comment]
> Lgtm! This might not pass the analyzer though since we don't have the melos action in here yet.

Should I add it on this PR?

**Comment by spydon** [comment]
> > Lgtm! This might not pass the analyzer though since we don't have the melos action in here yet.
> 
> Should I add it on this PR?

You can try if you want, I haven't tried it yet, so you might run into some issues. :grimacing:

**Review by wolfenrain — APPROVED** [review]
LGTM

**Pull request merged**
