### PR TITLE
Added a simple makefile for flame package

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

Small Makefile to simplify common tasks during development.

If this proves useful, a similar makefile can be added in the future to other flame projects.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [ ] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `flutter format` and the `flutter analyze` does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Comment by spydon** [comment]
I vote no for this, imho Makefiles should be deprecated with their obscure syntax.
If it would have been a standard in the Flutter world I would have voted yes just to keep consistency, but luckily it is not. :smile:

**Comment by erickzanardo** [comment]
> I vote no for this, imho Makefiles should be deprecated with their obscure syntax. If it would have been a standard in the Flutter world I would have voted yes just to keep consistency, but luckily it is not. 😄

I agree, it is just wrapping things that are already available on the Flutter CLI anyway.

**Comment by st-pasha** [comment]
The purpose of this makefile is not to implement the build process (which was the original purpose of makefiles, now outdated), but to provide a simple way to perform common developer tasks from CLI.

For example, I need to run `flutter analyze` and `flutter format` before each push. They have to run in that particular order. It's much easier to say `make format` then. Similarly for coverage. It's easier to say `make coverage` then trying to remember and then typing out the necessary instructions.

**Comment by spydon** [comment]
> For example, I need to run `flutter analyze` and `flutter format` before each push. They have to run in that particular order.
This sounds very much like a setup for individual developers, I think most have this integrated into their IDE.

> then trying to remember and then typing out the necessary instructions.
Now it will be two ways of doing things instead, going via the Makefile, or straight to the flutter CLI, and to keep consistency with other Flutter projects we shouldn't invent a new way of doing things I think.

> How do you guys usually generate coverage?
For me at least, I very rarely generate that myself, but let the GitHub action generate that. The few times I do generate that myself I simply press `ctrl+r` and type `cov` and it'll pop up.

**Comment by st-pasha** [comment]
> This sounds very much like a setup for individual developers

Absolutely. Some developers will have powerful IDEs with everything integrated. Others won't be so lucky. This makefile helps those others, without negatively affecting the first group.

> Now it will be two ways of doing things instead

As you have mentioned before, there are already two ways of doing this: one is via the IDE magic button, another is via the flutter command in the terminal. So, this PR adds a third way: via the make command. I don't think having multiple ways to accomplish the same task is bad, if those ways have different sets of pros and cons.

> I simply press ctrl+r and type cov and it'll pop up.

This obviously only works on your computer.

I mean, we have the question "does your PR reduce coverage?" in the PR checklist, so there should be at least some easy way for a contributor to verify whether that's true or not.

**Comment by spydon** [comment]
> Absolutely. Some developers will have powerful IDEs with everything integrated. Others won't be so lucky. This makefile helps those others, without negatively affecting the first group.

 We don't add IDE specific settings to the repo, so neither should we have something that is only targeted to the small group that is not running an IDE, after all the recommended way from Flutter when installing it is either Android Studio or VSCode. And I mean, even Erick that it running pure vim is voting this down.

> As you have mentioned before, there are already two ways of doing this: one is via the IDE magic button, another is via the flutter command in the terminal. So, this PR adds a third way: via the make command. I don't think having multiple ways to accomplish the same task is bad, if those ways have different sets of pros and cons.

The user knows that it goes through flutter when that happens, and it is usually done on save, so no active action to perform this. If I see a makefile in a project I would think that that is the project owners preferred way of running things.

> This obviously only works on your computer.
Yeah, it was only an example since you said you had a hard time remembering the command, but the point is that you shouldn't need to remember it, the GitHub action will do this for you.
 
> I mean, we have the question "does your PR reduce coverage?" in the PR checklist, so there should be at least some easy way for a contributor to verify whether that's true or not.
We could rephrase that to that the cicd doesn't report reduced coverage. We could even add coveralls like we have on `ordered_set` if we want it to be a bit more visual, but that should be discussed in an issue.

Anyhow, we are discussing something that hasn't been an issue for any contributor that we have heard of, if we would have seen that the community had problems with this, we'd probably bring back the script folder that we used to have and the coverage script that was in there. I'll close this since none in the team doesn't wants us to introduce a makefile.

**Pull request closed without merging**
