### PR TITLE
fix: Fix warnings/errors in documentation

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

Also, added an admonition for a "Deprecated" block.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [-] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples`.

## Breaking Change

- [-] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
Lgtm, we should really get a mardown linter

**Review by spydon — APPROVED** [review]

**Comment by st-pasha** [comment]
> we should really get a mardown linter

Maybe we could simply run `make html` inside the `doc/_sphinx` folder, as one of the PR checks.

**Comment by spydon** [comment]
> Maybe we could simply run `make html` inside the `doc/_sphinx` folder, as one of the PR checks.

How long does it take to run?

**Comment by st-pasha** [comment]
Like, 10 seconds on my computer.

**Comment by spydon** [comment]
> Like, 10 seconds on my computer.

Then it is probably like 20 in the pipeline, but we can put it as a parallel step so that it doesn't affect the total time.

**Pull request merged**
