### PR TITLE
chore: Update rive package to 0.13.5

### PR DESCRIPTION
**Pull request by NashIlli**
Description
Allow new features from Rive, like integrated audio and improve performance in 32 bits devices.

Checklist
I have followed the [Contributor Guide] when preparing my PR.
[-] I have updated/added tests for ALL new/updated/fixed functionality.
[-] I have updated/added relevant documentation in docs and added dartdoc comments with ///.
I have updated/added relevant examples in examples or docs.
Breaking Change?
No, this PR is not a breaking change.

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Review by ufrshubham — COMMENTED** [review]
@NashIlli, rive component tests are failing at [set-up](https://github.com/flame-engine/flame/actions/runs/9219863744/job/25365754636?pr=3159#step:5:1672) with the newer version

**Comment by NashIlli** [comment]
@ufrshubham

I've been investigating the issue, and it appears to be a known problem with the Rive library specifically affecting tests. The details are explained in this [GitHub issue comment](https://github.com/rive-app/rive-flutter/issues/354#issuecomment-2084677570).

Unfortunately, this is a limitation that they are not able to address quickly, which means I am unable to resolve the test error during setup at this time. But they said that it's only a "Testing time problem"

Please review the linked discussion for more context.

**Review by champ96k — COMMENTED** [review]
LGTM

**Comment by spydon** [comment]
I'll close this since it won't be doable until this one is fixed: https://github.com/rive-app/rive-flutter/issues/354

**Pull request closed without merging**
