### PR TITLE
example: Add Raycast example for flame_forge2d

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description

This PR adds a new sample in flame_forge2d for Raycast. It contains a sample implementation for finding nearest and farthest fixtures along the casted ray. Here is how it works, two rays (red and blue) are fired from same starting point with mouse position as the target. Red ray always stops at the nearest fixture and blue ray always stop at the farthest fixture. Paint of fixtures are changed depending on which ray hits it. If both rays hit the same fixture, it turns yellow.

https://user-images.githubusercontent.com/33748002/146823360-4e8b30c1-0d0e-44b0-8d25-61a8fb42bc0d.mp4

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the
relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added relevant examples in `examples`.
- (NA) I have updated/added tests for ALL new/updated/fixed functionality.
- (NA) I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change. (Indicate it in the [Conventional Commit] prefix with a `!`,
  e.g. `feat!:`, `fix!:`).
- [x] No, this is *not* a breaking change.

## Related Issues

NA

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
Nice! Could you add a short screen capture of the example to the description so that reviewers don't have to checkout your branch to see it?

**Comment by ufrshubham** [comment]
Added a video showing the demo of new sample.

**Review by spydon — APPROVED** [review]

**Comment by st-pasha** [comment]
Why is it that the ray sometimes stops short (for example, at 0:14 in the video)?

**Comment by spydon** [comment]
> Why is it that the ray sometimes stops short (for example, at 0:14 in the video)?

The example is using the `onMouseMove` detector and the rays are going to where the mouse is, with a small offset.

**Comment by ufrshubham** [comment]
Oh, that is because the target for raycast is mouse position. If no fixture is hit within start point to mouse position range, it stops at the mouse position. I forgot to turn on mouse capture while recording the video, that is why it looks a bit confusing.😅

**Comment by st-pasha** [comment]
Ah, I see, makes sense.

What about 0:17 when the blue ray goes through the white rectangle without hitting it?

**Pull request merged**
