### PR TITLE
feat: Add isometric support for flame_tiled

### LINKED ISSUE #1882: Isometric support in `flame_tiled`
# What could be improved
`flame_tiled` (and thus flame) could support Tiled's isometric tile maps.

image

# Why should this be improved
Gota have that shadowrun returns isometric feel.

# Any risks?
Doesn't seem like it at first glance; but I'm not an expert.  I didn't look into the painted layer. I didn't try to render objects from the object layer.

# More information

`renderable_tile_map.dart` does have enough information: i.e. the `TileMap`'s `MapOrientation` is known. In the `_RenderableTileLayer._cacheLayerTiles` it is possible to:

1. cache the `halfTile` outside of the loops.
2. Test the orientation in the inner loop to solve for the offsets:

```dart
          if (_map.orientation == MapOrientation.isometric) {
            offsetX = halfTile.x * (tx - ty);
            offsetY = halfTile.y * (tx + ty);
          } else {
            offsetX = ((tx + .5) * size.x);
            offsetY = ((ty + .5) * size.y);
          }

          offsetX += (layer.offsetX * scale);
          offsetY += (layer.offsetY * scale);
```

3. and then switch between how to add the batch transform:

```dart
            if (_map.orientation == MapOrientation.isometric) {
              batch.add(source: src, offset: Vector2(offsetX, offsetY));
            } else {
              final scos = flips.cos * scale;
              final ssin = flips.sin * scale;

              batch.addTransform(...
```

### PR DESCRIPTION
**Pull request by jtmcdole**
* Updates some forEach to regular for() loops
* Adds golden test with license free tilemaps

# Description

Adds support for **isometric** Tiled files.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

Do tests count as "examples"?

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1882

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Nice! Good job

**Comment by jtmcdole** [comment]
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

:)

**Comment by spydon** [comment]
> > Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
> 
> :)

I'm waiting for a second review

**Comment by jtmcdole** [comment]
Ah - solid!  I'm looking at hex tiles now... for no other reason than completeness.

**Review by erickzanardo — APPROVED** [review]

**Pull request merged**
