### PR TITLE
Make prefix configurable for image and asset loading

### PR DESCRIPTION
**Pull request by luanpotter**
Fixing https://github.com/flame-engine/flame/issues/715

### CODE REVIEW

**Review by erickzanardo — COMMENTED** [review]
Changes LGTM, but we should mention this new feature on the docs and add a CHANGELOG entry

**Comment by luanpotter** [comment]
I can add to the changelog, but I am not sure if such a small edge case is worth changing the documentation for...

**Comment by erickzanardo** [comment]
> I can add to the changelog, but I am not sure if such a small edge case is worth changing the documentation for...

It sure is, otherwise how can people know that they have a different prefix? I think just a small paragraph on the structure section of our docs would be enough

**Comment by luanpotter** [comment]
They would look at the code to see what the prefix is and clearly see how to change it. But if you want I will add to the docs.

**Comment by erickzanardo** [comment]
> They would look at the code to see what the prefix is and clearly see how to change it. But if you want I will add to the docs.

Looking at the code is never enough, look at the amount of questions we get on AP from people asking how to stop music played by AudioCache...

**Comment by luanpotter** [comment]
> Looking at the code is never enough, look at the amount of questions we get on AP from people asking how to stop music played by AudioCache...

I don't think those people would look at docs either, in fact we say how it works on the docs and readme on AP as well :p

**Review by erickzanardo — APPROVED** [review]

**Comment by ponderMuse** [comment]
Hi,

I have started placing most of a game's code into a separate package which is then used by two different applications (one for mob and one for browsers) so the capability of having Flame load assets from package dependencies is certainly handy.

Are there any estimates as to when this updated code is likely to make it into master?

Cheers,
PM

**Comment by spydon** [comment]
@ponderMuse this was released with `rc9` and `rc10` is the newest version.

**Comment by ponderMuse** [comment]
@spydon I was using rc8. Have now updated to rc9 after your comment and can now load assets through package as needed. Cheers!

**Comment by spydon** [comment]
> @spydon I was using rc8. Have now updated to rc9 after your comment and can now load assets through package as needed. Cheers! 

Why not use rc10? :)

**Comment by ponderMuse** [comment]
@spydon can do if it is available. It's just that [here](https://pub.dev/packages/flame/install) still shows rc9 as being the latest pre-release.

**Comment by spydon** [comment]
> @spydon can do if it is available. It's just that [here](https://pub.dev/packages/flame/install) still shows rc9 as being the latest pre-release.

Yeah, pub is ordering them in a weird way. rc10 is the newest.

**Comment by ponderMuse** [comment]
@spydon I have tried rc10 but my project errors with:

The function 'TextConfig' isn't defined.

rc9 has the class in package:flame/src/text_config.dart).

Where can I find TextConfig in rc10 or similar?

**Comment by spydon** [comment]
@ponderMuse these discusssions don't really fit on this PR, please join our discord to ask more questions https://discord.com/invite/pxrBmy4 (Our docs are updated for how to use text in rc10 too)

**Comment by ponderMuse** [comment]
I will take a look at the docs. Thanks for all the good help today @spydon

**Pull request merged**
