### PR TITLE
fix bug in the Box2DGame's add and addLater method , when the Compone…

### PR DESCRIPTION
**Pull request by dinoandcat**
…nt extends BodyComponent and mixin HasGameRef or other mixins ,the mixins will not be set correctly

# Description
fix bug in the Box2DGame's add and addLater method , when the Component extends BodyComponent and mixin HasGameRef or other mixins ,the mixins will not be set correctly

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [ ] I have made corresponding changes to the documentation
- [ ] I have added examples for new features in `doc/examples`
- [ ] The continuous integration (CI) is passing

### CODE REVIEW

**Comment by spydon** [comment]
It is a valid bug that you have found, but with this solution the update function will be called twice for each iteration.

**Review by spydon — CHANGES_REQUESTED** [review]
It is a valid bug that you have found, but with this solution the update function will be called twice for each iteration.

**Review by spydon — APPROVED** [review]
Forgot how preadd works, it looks good.

**Review by spydon — CHANGES_REQUESTED** [review]
@dinoandcat now you commited a lot of other changes too, was that accidental?

**Comment by dinoandcat** [comment]
@spydon Sorry for that, i forget this PR has not merged . I has reset the HEAD to the front commit.

**Comment by spydon** [comment]
Great, please add a line in the `CHANGELOG.md` file too, under `[NEXT]`.

**Review by spydon — APPROVED** [review]
Lgtm!

**Review by renancaraujo — APPROVED** [review]

**Pull request merged**
