### PR TITLE
ci: Inline analyze warnings

### PR DESCRIPTION
**Pull request by spydon**
# Description

This helps our contributors to see the warnings from the analyzer directly in the PR.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by munsterlander** [comment]
This is needed because a PR was merged that should have failed analyzation.  Updating my PR with the current main then caused a ripple effect of errors.  I have cleaned up lib/main.dart and reorganized all the routes that had been hodge-podged together.

**Comment by spydon** [comment]
> This is needed because a PR was merged that should have failed analyzation. Updating my PR with the current main then caused a ripple effect of errors. I have cleaned up lib/main.dart and reorganized all the routes that had been hodge-podged together.

We already have an analyzer in the pipeline, the only thing this does is giving the warnings inline.
Which PR should have failed the analyzer?

**Review by luanpotter — APPROVED** [review]
Nice! Just remove the example before merging haha

**Comment by munsterlander** [comment]
> > This is needed because a PR was merged that should have failed analyzation. Updating my PR with the current main then caused a ripple effect of errors. I have cleaned up lib/main.dart and reorganized all the routes that had been hodge-podged together.
> 
> We already have an analyzer in the pipeline, the only thing this does is giving the warnings inline. Which PR should have failed the analyzer?

I may have spoke to fast, but what occurred was using the github web update branch in my pr, then it started failing.  It had to do with ScaleBy and ScaleTo being out of order in the imports, but I suspect the Sequence import messed that all up.  Regardless, just opening in VSC and then quick fix reorder did the trick.

**Pull request merged**
