### PR TITLE
feat: Adding way to configure a layer paint in flame tiled

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Creates a configuration in Flame Tiled that allows developers to use custom paint objects which can be useful when we need to render tilesets that require a different Paint configuration other than the default one. Like low rez pixel art tilesets which benefits from using filterQuality.none

## Checklist

- [ ] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Related Issues

Replace or remove this text.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
This does things a bit differently than what we do everywhere else where we pass along a `Paint` object. Meanwhile this looks quite handy, shouldn't we first and foremost go for consistency?

I also don't understand fully, why is only the `opacity` an input to the factory function?

**Comment by erickzanardo** [comment]
> This does things a bit differently than what we do everywhere else where we pass along a `Paint` object. Meanwhile this looks quite handy, shouldn't we first and foremost go for consistency?
> 
> I also don't understand fully, why is only the `opacity` an input to the factory function?

Yeah, so, from what I understood from Flame Tiled code (I am still getting used to all of its structure haha). There is one paint per layer. That paint should contain the opacity of such layer, hence why the factory receives the opacity, so the paint can be built taking that into consideration. I am not sure how we could do if `TiledComponent` received the paint object directly instead, because that object would already arrive built to the layer and it would be built without the layer opacity.

Usually I would be more for the consistency, but in this case I don't see how we could accommodate by passing the objects.

**Comment by spydon** [comment]
> Yeah, so, from what I understood from Flame Tiled code (I am still getting used to all of its structure haha). There is one paint per layer. That paint should contain the opacity of such layer, hence why the factory receives the opacity, so the paint can be built taking that into consideration. I am not sure how we could do if `TiledComponent` received the paint object directly instead, because that object would already arrive built to the layer and it would be built without the layer opacity.
> 
> Usually I would be more for the consistency, but in this case I don't see how we could accommodate by passing the objects.

It should be possible to pass down a factory function through the `FlameTileLayer`, exactly the same path as the `filterQuality` goes today I think? Going down the route of having these disconnected singletons is a bit dangerous I think.

**Comment by erickzanardo** [comment]
Ah, alright, I thought you mentioned passing down the instantiated objects, not the factory itself. That we can do!!!!

**Review by spydon — APPROVED** [review]

**Pull request merged**
