### PR TITLE
feat: add PlaceholderComponent

### PR DESCRIPTION
**Pull request by lukepighetti**
# Description

I was unable to find any way to quickly build placeholder components despite support from the Discord server. I created `PlaceholderComponent` to make it fast to create colored rectangle components that can easily be swapped out for `SpriteComponent` at a later date. 

If the opinion on this PR is favorable, I will update the documentation.

I am also happy to close this PR if there is already a fast way to prototype components in Flame.

### Example
```dart
class MyCharacter extends PlaceholderComponent {
  @override
  Future<void> onLoad() async {
    size = Vector2(50, 50);
    color = Colors.red;
  }
}
```

### Screenshots

Screen Shot 2022-11-12 at 8 32 54 PM

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by ufrshubham** [comment]
Isn't `RectangleComponent` already solving the same thing?

**Comment by lukepighetti** [comment]
I wasn't able to paint RectangleComponent a solid color, do you have an example that is known to work?

**Comment by ufrshubham** [comment]
> I wasn't able to paint RectangleComponent a solid color, do you have an example that is known to work?

This one has some `RectangleComponent`s with different colors: https://examples.flame-engine.org/#/Effects_EffectControllers

**Comment by spydon** [comment]
I'll close this since it pretty much does the same as RectangleComponent`.

Also a hint for the future, try to not create new objects in the render loop like you do with the `Paint` here, since that will result in lots of unnecessary objects that are created and might bring down your performance.

**Comment by lukepighetti** [comment]
RectangleComponent does not appear to work as expected, can someone tell me what I'm missing?

Screen Shot 2022-11-13 at 8 29 02 AM

```dart
class MyGame extends FlameGame {
  final rectangle = MyRectangle();
  final placeholder = MyPlaceholder();

  @override
  Future<void>? onLoad() async {
    add(rectangle);
    add(placeholder);
  }
}

class MyRectangle extends RectangleComponent {
  @override
  Future<void> onLoad() async {
    debugMode = true;
    size = Vector2(50, 50);
    position = Vector2(150, 150);
    paint = Paint()..color = Colors.green;
  }
}

class MyPlaceholder extends PlaceholderComponent {
  @override
  Future<void> onLoad() async {
    debugMode = true;
    size = Vector2(50, 50);
    position = Vector2(250, 150);
    color = Colors.red;
  }
}
```

**Comment by ufrshubham** [comment]
> RectangleComponent does not appear to work as expected, can someone tell me what I'm missing?

Right now, `RectangleComponent` needs the size to be set while construction. If you setup your `MyComponent` properly to forward parameters to `super`, it will work.

```dart
class MyGame extends FlameGame {
  final rectangle = MyRectangle(
    size: Vector2(50, 50),
    position: Vector2(150, 150),
    paint: Paint()..color = Colors.green,
  );

  @override
  Future<void>? onLoad() async {
    add(rectangle);
  }
}

class MyRectangle extends RectangleComponent {
  MyRectangle({
    super.position,
    super.size,
    super.angle,
    super.anchor,
    super.children,
    super.priority,
    super.paint,
  });
}
```

**Comment by lukepighetti** [comment]
While I still find the current behavior of RectanglePaint not easy enough for new users to prototype components, I am going to track this as an issue here: https://github.com/flame-engine/flame/issues/2166

**Pull request closed without merging**
