### PR TITLE
fix: Disallow mutatation of `SpriteAnimationGroupComponent.animations`

### PR DESCRIPTION
**Pull request by spydon**
# Description

Many users try to modify the `SpriteAnimationGroupComponent.animations` map, but that doesn't work since it has to go through the setter, so this PR makes the returned map from the getter unmodifiable.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

**Comment by erickzanardo** [comment]
Is it the same way in the SpriteGroupComponent?

**Comment by spydon** [comment]
> Is it the same way in the SpriteGroupComponent?

I thought it didn't, but it does!

**Comment by spydon** [comment]
@erickzanardo this is the follow-up to fix it for `SpriteGroupComponent`:
https://github.com/flame-engine/flame/pull/3185

**Comment by erickzanardo** [comment]
> @erickzanardo this is the follow-up to fix it for `SpriteGroupComponent`:
> 
> https://github.com/flame-engine/flame/pull/3185

Cool, I am both right and late hahahha

**Pull request merged**
