### PR TITLE
docs: Fix mermaid graphs

### LINKED ISSUE #2465: Make the Component lifecycle graph readable
# What could be improved
It is currently very hard to read the Component Lifecycle graph:
image

# Any risks?
No.

# More information
The graph is generated so it should be fairly easy to just update the colors it uses for "Runs Once" and for the bottom arrow.

### PR DESCRIPTION
**Pull request by immadisairaj**
Styling of the graphs were not proper and custom stylings were being overrided by the default styling. This PR fixes that issue. There is another issue where the arrow is not shown properly and a dimmed line is shown, this is because of improper syntax, that also has ben changed in this commit. And lastly, the component lifecycle graph onLoad and low-level game api graph are fixed.

# Description

The `yellow` styling is defined before `default` styling which ignores `yellow` styling. So, moving it after `default` will work as expected.

Also, the syntax `A-- This is a text .->B` is not a syntax. So, changing it to either `--` or `-. | .-` completely will fix the non arrow showing line.

This PR changes 3 graphs:

| Before | After |
| - | - |
| Screenshot 2023-04-11 at 20 47 17 | Screenshot 2023-04-11 at 20 47 43 |
| Screenshot 2023-04-11 at 20 48 33 | Screenshot 2023-04-11 at 21 26 27 |
| Screenshot 2023-04-11 at 20 49 28 | Screenshot 2023-04-11 at 21 27 26 |

## Checklist
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [-] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?
- [-] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
Closes #2465

### CODE REVIEW

**Comment by spydon** [comment]
The arrow from `onRemove` could go directly to `onGameResize` now too.

**Comment by immadisairaj** [comment]
Now the new graphs will be:
1. Screenshot 2023-04-11 at 21 11 47
2. Screenshot 2023-04-11 at 21 11 21

If this is alright, I will push them at once.

**Comment by spydon** [comment]
> Now the new graphs will be:
> 1. Screenshot 2023-04-11 at 21 11 47
> 2. Screenshot 2023-04-11 at 21 11 21
> 
> If this is alright, I will push them at once.

Exactly
I think the text in the bottom can be changed to "If added to a new parent", if it fits.

**Comment by spydon** [comment]
Oooh right, and `Game` is no longer a mixin, but an abstract class, so the yellow box could change to that. It is still used as a mixin from `FlameGame` so that part is still correct.

**Comment by immadisairaj** [comment]
> Oooh right, and `Game` is no longer a mixin, but an abstract class, so the yellow box could change to that. It is still used as a mixin from `FlameGame` so that part is still correct.

So, just changing the `Mixin` to `Abstract Class` would be fine?

**Review by spydon — APPROVED** [review]
Good stuff, thanks!

**Comment by immadisairaj** [comment]
Also a doubt, should the `If added to a new parent` be a normal line or dotted line is good?

**Comment by immadisairaj** [comment]
And, I think that the [docs near low-level game api graph](https://docs.flame-engine.org/main/flame/game.html#low-level-game-api) has to be updated? (as you mentioned it was outdated).

Maybe it can go to a new issue if required?

**Comment by spydon** [comment]
> Also a doubt, should the `If added to a new parent` be a normal line or dotted line is good?

It can be dotted, I think that is clear enough.

> And, I think that the [docs near low-level game api graph](https://docs.flame-engine.org/main/flame/game.html#low-level-game-api) has to be updated? (as you mentioned it was outdated).
> 
> Maybe it can go to a new issue if required?

Ah yes, let's turn that into a new issue.

**Pull request merged**
