### PR TITLE
👌 Use `Offset` type directly in `JoystickAction.update` calculations

### LINKED ISSUE #606: Improve `JoystickAction.update` logic
existing code, but this could be:

```dart
final nextPoint = Vector2(nextX, nextY);
// ...
final Offset diff = _rectBackgroundDirection.center.toVector2() + nextPoint - _rectAction.center;
_rectAction = _rectAction.shift(diff.toOffset());
```

_Originally posted by @luanpotter in https://github.com/flame-engine/flame/pull/603#discussion_r551152386_

### PR DESCRIPTION
**Pull request by lig**
# Description

Improved code a bit to utilize `Offset` support for `+` and `-` operators.

Fixes #606 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on the latest `master`
- [x] I have formatted my code with `flutter format`
- [x] The continuous integration (CI) is passing
- [x] Changelog entry

### CODE REVIEW

**Comment by lig** [comment]
The original suggestion by @luanpotter was to use `Vector2` type. It's turned down that using `Offset` produces less code still allowing direct calculations with it.

**Review by spydon — APPROVED** [review]
Nice, much easier to read too!

**Comment by lig** [comment]
> Nice, much easier to read too!
> 
> Wouldn't it be the same amount of code qith Vector2 though? 🤔
> We are trying to use Vector2 as much as possible for these datatypes.

The resulting value of the expression needs to be converted to Offset to pass it further. nextPoint we are controlling fully here. However, other values are Offsets. Using Vector2 results in 3 type conversions: to Vector2 for two input values and converting the result back to Offset.
I believe that is better to avoid conversions and much at possible. For Vector2 to be adopted more widely the values should be created as Vector2 in the first place.

**Comment by lig** [comment]
> Also, please add a changelog line.

Ok, I want able to come up with anything meaningful for this change;) but I'll figure something out.

**Comment by spydon** [comment]
Makes sense, and I agree

**Review by renancaraujo — APPROVED** [review]

**Review by wolfenrain — APPROVED** [review]

**Review by erickzanardo — CHANGES_REQUESTED** [review]
LGTM, only missing the changelog entry, gonna mark a request changes on the PR so we don't merge this before having the entry

**Review by luanpotter — APPROVED** [review]
LGTM

**Review by erickzanardo — APPROVED** [review]

**Pull request merged**
