### PR TITLE
fix: Possibility to create RenderableTiledMap from TiledMap

### LINKED ISSUE #1533: [flame_tiled] add availability to loading TiledMap directly
# What could be improved
Change `_loadMap` to public and create new method `static Future<RenderableTiledMap> fromMap(TiledMap map, Vector2 destTileSize)`
https://github.com/flame-engine/flame/blob/cae8c0ceb395416ed86fd644c1dd7790eae127ca/packages/flame_tiled/lib/src/renderable_tile_map.dart#L106

# Why should this be improved

Currently, there are only `fromFile` and `fromString` methods for making `RenderableTileMap` and cannot make `TiledMap` directly.
The `fromString` uses `_loadMap` to loading `TiledMap` and loads the image directly at the next line.
As a result, there is no chance of retrieving and manipulating the map's image path before the image is actually loaded.
https://github.com/flame-engine/flame/blob/cae8c0ceb395416ed86fd644c1dd7790eae127ca/packages/flame_tiled/lib/src/renderable_tile_map.dart#L108

Imagine that we want to get images from a remote URL. 
But `_loadImages` loads SpriteBatch directly before we know the path of the imageSets of TileMap.
So we cannot inject the image files from a remote URL before flame loads it from local assets.

# Any risks?

Misusing of loadMap..? but this isn't very common.

# More information

Are you interested in working on a PR for this?  **YES**

It is a long way to go to acheving dynamically fetching maps.. I think this one is starting.

### PR DESCRIPTION
**Pull request by Hwan-seok**
# Description
Fixes #1533 

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
> Isn't it a bit inconsistent that `loadMap()` returns a `TiledMap`, while `fromMap()` returns a `RenderableTileMap`?

Good catch, maybe `fromMap` -> `fromTiledMap` since this is in the `RenderableTileMap` class I think it makes sense to return a `RenderableTileMap`. And maybe `loadMap` should actually be living in the `TiledMap` class?

**Comment by spydon** [comment]
Created: https://github.com/flame-engine/tiled.dart/pull/42
This PR should be able to use that one instead of `loadMap`.

**Comment by spydon** [comment]
Created: https://github.com/flame-engine/tiled.dart/pull/42
This PR should be able to use that one instead of `loadMap`.

**Comment by spydon** [comment]
@Hwan-seok If you do a `pub upgrade` now `tiled.dart` should expose `TiledMap.fromString` that you can use instead of `loadMap`. You have to send in `FlameTsxProvider.parse` to the method as the second argument.

**Comment by Hwan-seok** [comment]
@spydon 
I got it, I will fix the PR.

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
> @spydon 
> I got it, I will fix the PR.

Super, looks great! I'll do a release of this tonight. :)

**Review by wolfenrain — APPROVED** [review]
LGTM

**Pull request merged**
