### PR TITLE
fix: Flame_rive now can load Nested Artboards and update to 0.9.0 rive package (now can load rive listeners too),

### LINKED ISSUE #1692: Nested artboards in Rive files doesn't work if you use RiveComponent
# Current bug behaviour
Nested artboards in Rive files doesn't appear if you use RiveComponent, because this use RiveFile like is comented in [this issue](https://github.com/rive-app/rive-flutter/issues/193). You would use RiveAnimation.asset() or wait to Rive team solve the bug.

# Expected behaviour
Nested artboards render and animate.

# Steps to reproduce
Add a RiveComponent with Nested Artboards

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-44-generic, locale es_ES.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

# More environment information

log information in this code block
```

### PR DESCRIPTION
**Pull request by nmarafo**
# Description

Is a solution to Closes  #1692 and updatting to rive 0.9.0 flutter package

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues
Closes  #1692 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by st-pasha** [comment]
Note: in the PR description write `Closes #1692` instead of simply `#1692` -- this enables GitHub magic that will ensure the upstream issue is closed automatically when this PR is merged.

**Review by erickzanardo — APPROVED** [review]

**Comment by spydon** [comment]
Published flame_rive 1.4.0 including this change.

**Comment by NashIlli** [comment]
Hello! I understand I can use Rive Listeners in my Flame Game. I couldn't make it work. It works well in a Flutter (not flame) app. Could you provide an example of Rive Listeners in a Flame Game?

**Comment by nmarafo** [comment]
In Flame Engine, .riv files are into a RiveComponent, so you must use Tap Events or CollisionCallbacks to activate the inputs into your .riv file. If you want to use the rive listeners, you must parse de Rive Widget from Flutter like in this example: [Widget example in forge2D](https://github.com/flame-engine/flame/blob/main/examples/lib/stories/bridge_libraries/forge2d/widget_example.dart)

**Comment by NashIlli** [comment]
Ok, I understand. I tried and it works following the example you provided.

Do you think that is it possible to add rive listeners feature to RiveComponent? Or "by design" or anything it isn't possible? Because of course there are some limitations working with overlays.

Thanks for your help!

**Comment by spydon** [comment]
If I understand rive listeners correctly they don't offer anything more than what we already have in Flame, you can already add a `TapCallback` etc to the `RiveComponent` and change the state of the rive state machine, just like @nmarafo says.

**Comment by NashIlli** [comment]
I agree about the final product will be the same.

But Rive listeners offers the possibility to a designer/animator configure some listeners and, if it is necessary, we can handle the change of the state in our game.
For example, a simple button. A designer can add a "on hover" listener to trigger a animation of the State Machine. And by programming, a developer can add the "on click" listeners. Of course a developer can also add the "on hover" listener, but it could be better if it is added by the deseigner.

Furthermore, if you have 2 or more elements that a user can interact inside a Rive Animation. If I understand correctly, in Flame you can add listeners to the whole RiveComponent, but not to a part. For example, you can have two bush and whe the user click the bush A it will shake and when the user click the bush b it will show a flower. That functionality can only be achieved with rive listeners if the animation is exported as a whole.

**Comment by spydon** [comment]
Alright, that makes sense. You'd have to add hitboxes if you'd want only specific parts of a component to react to different inputs.
I don't know how how hard it would be to make a similar thing as their listeners for Flame, I suspect it would be quite a lot of work, but I suggest that you create an issue for it and it can be discussed there. :)

**Comment by nmarafo** [comment]
In this example: https://github.com/nmarafo/rive_listeners_example/blob/master/lib/main.dart, you can see how use a rive file with listener using "Hoverable". In asset directory you have "new_file.riv". Thius file has a listener called "hover".

**Pull request merged**
