### PR TITLE
fix: Optimize the contact callback process.

### PR DESCRIPTION
**Pull request by BlockRen**
Sorry for late. Yes, this is a breaking change, it's my mistake for description.

The original code may cause a bug when register more than one same class, such as I register two Football. Then the two class both will be selected in the functions of 'ContactTypes' and both will be callback. So maybe the two balls will both move if we don't do anything else to make the two Football different.

About "why there are no need to register the callbacks". Because the 'Contact' call back from the forge2d (beginContact, endContact) already tell us both the contacted objects. 'Contact' includes the two bodies and the two fixtures that contacted. And we also can get the contacted object using the 'userData' of 'BodyDef'.

Using my modified code, the listening callback can be like below:

class Football extends PositionBodyComponent with ContactCallback {
  ...
  @override
  void begin(a, b, Contact contact) {
    // Here a is the Football, b is another contacted object.
  }

  @override
  void end(a, b, Contact contact) {}
}

---------------- new above --- old below --------------

# Description

The callback process is no need to do 'register' and 'forEach' loop to fetch.
There will be a problem when two same class A in the listener list, because the forEach and _mayCallback will callback the both but only one is in the contact.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the
relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have did tests for ALL new/updated/fixed functionality.
- [/] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [/] I have updated/added relevant examples in `examples`.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

YES, this is a breaking change.

## Related Issues

#1321

### CODE REVIEW

**Comment by spydon** [comment]
You'll have to explain a bit more what you are doing here, why is there no need to register the callbacks?

And also you have marked this as a non-breaking change, but since you are removing functions from `Forge2DGame` it is a breaking change. (Breaking changes are okay though)

**Comment by spydon** [comment]
@BlockRen it is failing the analyzer and the formatter (I can help you with those issues if you want), but more importantly I think I need the change explained to me to be able to properly review this.

**Review by abgutierrez — APPROVED** [review]
LGTM. 

Edit: I cannot remove my verification, apologies. Didn't see pending comments from @spydon, I agree with him.

**Comment by st-pasha** [comment]
@spydon Have you seen https://github.com/marketplace/actions/dart-analyze-with-annotations? It's similar to our analyzer, but reports directly into the PR.

**Comment by spydon** [comment]
> @spydon Have you seen https://github.com/marketplace/actions/dart-analyze-with-annotations? It's similar to our analyzer, but reports directly into the PR.

I have indeed, we have discussed adding it, don't remember what our conclusion was but we should definitely try it. And probably run it as a second non-mandatory step, since I guess that one can't be as nicely parallelized.

**Comment by wolfenrain** [comment]
> > @spydon Have you seen https://github.com/marketplace/actions/dart-analyze-with-annotations? It's similar to our analyzer, but reports directly into the PR.
> 
> I have indeed, we have discussed adding it, don't remember what our conclusion was but we should definitely try it. And probably run it as a second non-mandatory step, since I guess that one can't be as nicely parallelized.

Conclusion was: lets try it. Or in Lukas, leettsss dooo iiiiit

**Comment by spydon** [comment]
> LGTM.
> 
> Edit: I cannot remove my verification, apologies. Didn't see pending comments from @spydon, I agree with him.

@abgutierrez have you tried it?

**Comment by BlockRen** [comment]
> 

More explanation added in the comment. Thank you.

**Comment by BlockRen** [comment]
> @BlockRen it is failing the analyzer and the formatter (I can help you with those issues if you want), but more importantly I think I need the change explained to me to be able to properly review this.

More explanation added in the comment. Thank you.

**Comment by spydon** [comment]
> > @BlockRen it is failing the analyzer and the formatter (I can help you with those issues if you want), but more importantly I think I need the change explained to me to be able to properly review this.
> 
> More explanation added in the comment. Thank you.

Thanks! Could you update the example that is using contact callbacks in `flame_forge2d`?
https://github.com/flame-engine/flame/blob/main/packages/flame_forge2d/example/lib/contact_callbacks_sample.dart

**Comment by spydon** [comment]
Closing this in favor of #1547

**Pull request closed without merging**
