### PR TITLE
fix: correctly calculating frame length

### PR DESCRIPTION
**Pull request by oloshe**
Sorry I didn't double check this error in yesterday's pr due to my oversight, because the index starts from 0, and the calculated length should be incremented by 1。

### CODE REVIEW

**Review by spydon — APPROVED** [review]
And none of us caught it in code review either 😅

**Comment by oloshe** [comment]
> 

Yes, boundary check is so difficult to detect with the naked eye, I found this problem in actual use today

**Comment by st-pasha** [comment]
Shouldn't there be a test for this? Seems like a very easy thing to miss in subsequent refactors.

**Comment by spydon** [comment]
> I agree with that, but I don't seem to find any tests about `SpriteAnimationData`

Feel free to add a file for it, some old classes are missing test files.

**Pull request merged**
