### PR TITLE
Improved testing API

### PR DESCRIPTION
**Pull request by luanpotter**
# Description

<details>
<summary> ~~first proposal~~ </summary>
Proposal: make the createGame provider for the `flameTest` optional.
Advantages: cleaner, simpler for most use cases.
Disadvantages: not as type safe because if converts a compile error to a runtime error if T != Game (and dart doesn't have overloading).
Other option would be to create a new method where T===FlameGame and it calls this one (but would need to have a different name).
</details>

### Second Proposal

So I came up with a better idea. It came to me that from all the parameters required to run a test, there are two types:

* name and actually test -> these are of course always unique per test. can't have a test with duped name or code
* everything else -> these most commonly have a single value, if not for the entire application, at least for a set of tests

So the proposal is to split this into two steps. the common parameters are provided via the constructor and the test functions only take two parameters. now, when you do wanna change something, I provide a copy constructor. I considered optional parameters on the two test functions but I choose the copy constructor for two reasons: (1) promotes reuse of code between tests even when there are variations and (2, most importantly) the test functions signature now is identical to the test/widgetTest functions from the platform, so it looks more natural

Thoughts?

Note: just a proposal yet, I will (try) to add tests later (tests that test tests are hard haha)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [ ] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [ ] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [ ] I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
- [ ] I read and followed the [Flame Style Guide].
- [ ] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [ ] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [ ] No, this is *not* a breaking change.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database]. Indicate, which of these issues are resolved or fixed by this PR.*

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Comment by erickzanardo** [comment]
Leeeets do eeeet

**Comment by st-pasha** [comment]
Is there any reason why we can't have `FlameTester(MyGame())` and instead have to do `FlameTester(() => MyGame())?

**Comment by erickzanardo** [comment]
We need a fresh instance for each test case

**Comment by st-pasha** [comment]
> We need a fresh instance for each test case

Makes sense, thanks.

**Comment by luanpotter** [comment]
We will soon be able to do `FlameTester(MyGame)` with the dart 2.15! (constructor tear off)

**Pull request merged**
