### PR TITLE
feat: Move the _sphinx directory to flame-docs-site

### PR DESCRIPTION
**Pull request by spydon**
# Description

This is an intermediate solution to have the docs site not being tied to Flame tags.
It just moves the `_sphinx` directory to the flame-docs-site repo and then copies it in place every time it generates the docs for a tag. 

https://github.com/flame-engine/flame-docs-site/pull/5

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

## Breaking Change

- [x] No, this is *not* a breaking change.

## Related Issues

Related to #1768, but we will probably be able to come up with a better solution in the long run.

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

**Comment by spydon** [comment]
> But how would this process work if this directory is moved to another repo?

It will work the same as today, but instead of using the `_sphinx` directory from the checked out tag, it will use the latest `_sphinx` directory for all versions. See this PR: https://github.com/flame-engine/flame-docs-site/pull/5

I think it makes sense to separate the styling and functionality of the docs site from the actual content, because today if we get a bug in the functionality of the docs site that tagged version will always have that bug.

**Comment by st-pasha** [comment]
> It will work the same as today, but instead of using the _sphinx directory from the checked out tag, it will use the latest _sphinx directory for all versions. 

I still don't get it. Currently, in order to develop documentation (and be able to see the results), one would need to:
1. git clone flame repository (once)
2. cd into doc/_sphinx
3. pip install from the requirements file (once)
4. run make html
5. open the generated index.html file in the browser

But if the folder is in another repository, then what? How would the development process look like?

**Comment by spydon** [comment]
> But if the folder is in another repository, then what? How would the development process look like?

We can have a melos target that sets all that up, including pulling down the other repo.
If you have a better idea for how to separate them I'm all ears! Currently we're stuck with our latest released version not having searchable docs and we have to have a way to fix bugs in the functionality of the docs which doesn't only apply to `main` and future versions.

**Comment by st-pasha** [comment]
What do you think about the following:
1. No changes in this repository

Then, in the `flame-docs-site` repository we modify the `publish.sh` script to add the following steps:
```bash
tmp_sphinx_copy = $tmp_flame_src/../sphinx-copy

function main() {
  ...
  git clone https://github.com/flame-engine/flame.git $tmp_flame_src
  cd $tmp_flame_src

  # NEW:
  git checkout main
  cp -rf doc/_sphinx $tmp_sphinx_copy
  
  ...
}

function generate() {
  version=$1
  ...
  cd $tmp_flame_src
  git checkout -f $version
  
  # NEW
  rm -rf doc/_sphinx
  cp -rf $tmp_sphinx_copy doc/_sphinx

  ...
}
```

This way you always get the latest _sphinx when building a particular branch, but the development process in the flame repository is not affected.

**Comment by spydon** [comment]
I guess we could also keep it where it is, but only use the `main` `_sphinx` directory for all tags when we publish, then the current workflow would be kept.

**Comment by spydon** [comment]
> What do you think about the following:
> 
>     1. No changes in this repository
> 
> 
> Then, in the `flame-docs-site` repository we modify the `publish.sh` script to add the following steps:
> 
> ```shell
> tmp_sphinx_copy = $tmp_flame_src/../sphinx-copy
> 
> function main() {
>   ...
>   git clone https://github.com/flame-engine/flame.git $tmp_flame_src
>   cd $tmp_flame_src
> 
>   # NEW:
>   git checkout main
>   cp -rf doc/_sphinx $tmp_sphinx_copy
>   
>   ...
> }
> 
> function generate() {
>   version=$1
>   ...
>   cd $tmp_flame_src
>   git checkout -f $version
>   
>   # NEW
>   rm -rf doc/_sphinx
>   cp -rf $tmp_sphinx_copy doc/_sphinx
> 
>   ...
> }
> ```
> 
> This way you always get the latest _sphinx when building a particular branch, but the development process in the flame repository is not affected.

Haha, you must have posted that just seconds before me. Let's go with that then.

**Pull request closed without merging**
