### PR TITLE
Prevent multiple completions

### PR DESCRIPTION
**Pull request by renancaraujo**
Avoid errors like the one in #153

### CODE REVIEW

**Comment by luanpotter** [comment]
one question though, is it possible and does it make sense to 'unregister' the listener?

**Comment by renancaraujo** [comment]
Yes and yes.

**Comment by luanpotter** [comment]
Well, this solution is fine by me, we can merge this.

**Comment by luanpotter** [comment]
Except you must make your PR point to dev, not master! please fix that

**Comment by erickzanardo** [comment]
LGTM, just fix the branch and it is ready to be merged

**Comment by erickzanardo** [comment]
Actually, add an entry on CHANGELOG.md about this fix

**Comment by renancaraujo** [comment]
Everything up to date

**Comment by erickzanardo** [comment]
Thanks @renancaraujo

**Pull request merged**
