### PR TITLE
feat(overlays): Added the 'priority' parameter for overlays

### PR DESCRIPTION
**Pull request by raspberry-jenshen**
# Description

To sort overlays we can introduce a priority. 
Let's say my app contains several menus that can be displayed simultaneously, but I want my main menu displayed at first in the stack (at the bottom).

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — APPROVED** [review]
I was thinking this was going to be a breaking change, good job in not making it so. Lgtm!

**Comment by spydon** [comment]
I just realized that docs are missing @raspberry-jenshen, if you can just add a short paragraph and example for it here:
https://github.com/flame-engine/flame/blob/main/doc/flame/overlays.md

**Comment by raspberry-jenshen** [comment]
All done!

Please check @spydon 

Screenshot 2024-10-21 at 16 18 01

**Comment by spydon** [comment]
Some markdown linting issues, but otherwise it looks good :)
```
doc/flame/overlays.md:23:81 MD013/line-length Line length [Expected: 80; Actual: 129]
```

**Review by spydon — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
