### PR TITLE
test: Unit tests for event mixins - `DragCallbacks` and `TapCallbacks`

### LINKED ISSUE #2017: Unit tests for event mixins
# What could be improved

Currently the event mixins are not tested at, it would be good to improve the test coverage here.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/component_mixins
https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/flame_game_mixins
https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/game_mixins

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

### PR DESCRIPTION
**Pull request by ShwetaChauhan18**
# Description
- 🐛 fix: #2017: Unit tests for event mixins
-  Unit and Widget tests for Event Mixin
    - `DragCallbacks`
    - `TapCallbacks`
    - `MultiTouchDragDetector`
    - `MultiTouchTapDetector`

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
Closes #2017 

## Note:
- I will add more widget test in next PR

### CODE REVIEW

**Comment by spydon** [comment]
It would be good with some widget tests here, so that the gestures are coming directly from the widget and then propagates down to the mixins, because now the mixin functions are basically called directly with the correct information.
You can look at how it is done here:
https://github.com/flame-engine/flame/blob/main/packages/flame/test/events/flame_game_mixins/has_tappable_components_test.dart

Keep your current tests too though, they are also good!

**Comment by ShwetaChauhan18** [comment]
> It would be good with some widget tests here, so that the gestures are coming directly from the widget and then propagates down to the mixins, because now the mixin functions are basically called directly with the correct information. You can look at how it is done here: https://github.com/flame-engine/flame/blob/main/packages/flame/test/events/flame_game_mixins/has_tappable_components_test.dart
> 
> Keep your current tests too though, they are also good!

ok, got it

**Comment by ShwetaChauhan18** [comment]
> It would be good with some widget tests here, so that the gestures are coming directly from the widget and then propagates down to the mixins, because now the mixin functions are basically called directly with the correct information. You can look at how it is done here: https://github.com/flame-engine/flame/blob/main/packages/flame/test/events/flame_game_mixins/has_tappable_components_test.dart
> 
> Keep your current tests too though, they are also good!

@spydon : PR updated with more test cases

**Review by spydon — APPROVED** [review]
Good job!

**Review by erickzanardo — APPROVED** [review]

**Pull request merged**
