### PR TITLE
docs(ui): Improved accessibility

### LINKED ISSUE #2895: Documentation Improvements
# What could be improved
The following is valuable feedback that we got from Google:

**Feedback for Flame documentation**
1. It needs an introduction.
    * It lacks an explanation of what Flame is, what it does, how developers benefit.
    * The context for the entire ecosystem is missing.

2. It needs context.
    * Each section of the documentation lacks any “why” regarding the need for or use of the particular section.
    * Without context, it makes the information less approachable.

3. It needs conceptualization.
    * Each section lacks context for either Flutter or game development.
    * This could include references to Flutter via link or explanation as well as those for common game development concepts.

4. It needs to be more atomic.
    * Some pages should be sections (especially Components and Effects).
    * These sections, when broken up, would be easier to find.

5. It has links that need correction.
    * Some, like those at the bottom of Collision Detection, need to be fixed.

6. It has URLs that include URL-encoded characters like spaces.
    * All of the examples have URLs with spaces in them. That should be fixed.

7. It has many accessibility issues.
    * The color contrast between text and background is poor.
    * Many links lack usable text. (That is, they just link on the word “here”.)
    * Form labels and alt text are missing in places.

# Why should this be improved
Because we want good docs.

# Any risks?
No.

# More information
If you would like to work on a big specific part we can split it out to a separate issue, if you just want to do a small fix related to this issue there is no need to create a new issue.

### PR DESCRIPTION
**Pull request by alt-shreya**
# Description

* Improved color contrast ratio.
* Added discernible links and alt text for screen readers.
* Fixed broken links and redirected deprecated repos.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2895 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by spydon** [comment]
Awesome that you're working on this! Please add some screenshots with how it looks before and after the change.

**Comment by alt-shreya** [comment]
> Awesome that you're working on this! Please add some screenshots with how it looks before and after the change.

sure thing!

**Comment by spydon** [comment]
@alt-shreya did you want any input here before continuing?

**Comment by alt-shreya** [comment]
> @alt-shreya did you want any input here before continuing?

@spydon no, my apologies for the delay, I had to prioritise a project for another client.
I'll pick this up now!

**Comment by alt-shreya** [comment]
@spydon there seems to be a conflict with markdown-lint tests. I have to include long URLs that are greater than 100 characters, but I don't seem to be able to wrap them like normal text. Should I just ignore the failures of the MD013 tests?

**Comment by spydon** [comment]
> @spydon there seems to be a conflict with markdown-lint tests. I have to include long URLs that are greater than 100 characters, but I don't seem to be able to wrap them like normal text. Should I just ignore the failures of the MD013 tests?

You can just move them to the next line in the markdown file, they will still render as continues text as long as you don't do two line breaks.

**Comment by alt-shreya** [comment]
> You can just move them to the next line in the markdown file, they will still render as continues text as long as you don't do two line breaks.

I've tried this, but it raises another error: ````MD034 no-bare-URL````

**Comment by alt-shreya** [comment]
> > You can just move them to the next line in the markdown file, they will still render as continues text as long as you don't do two line breaks.
> 
> I've tried this, but it raises another error: `MD034 no-bare-URL`

All tests seem to be passing now :thinking:

**Review by spydon — APPROVED** [review]
Lgtm! Thanks for your contribution

**Comment by alt-shreya** [comment]
> Lgtm! Thanks for your contribution

Lessgoo! Looking forward to contributing more in the future! :tada:

**Pull request merged**
