### PR TITLE
feat: Allow RiverpodComponentMixin and RiverpodGameMixin on the same class

### LINKED ISSUE #2971: Allow ComponentRef access in RiverpodGameMixin
# What could be improved

I was wondering if it is possible to allow `RiverpodComponentMixin` and `RiverpodGameMixin` to be a mixin on the same class. Currently this is not possible due to the same variable name being used in both mixins (`_onBuildCallbacks`).
One example on how this could be used then:
```dart
class MyGame extends FlameGame with RiverpodGameMixin, RiverpodComponentMixin {
  @override
  void onMount() {
    addToGameWidgetBuild(() {
      ref.listen(pausedStateStreamProvider, (p0, p1) {
        if (p1.hasValue) {
         paused = p1.value!;
        }
      });
    });
    super.onMount();
  }
}
```

# Why should this be improved

It would make it easier to react upon provider changes on the Game instance level, for example to pause the game or do other things where access to the game instance is needed. Currently, a separate Component, which uses `findGame()` or `HasGameRef`, is needed for these use cases. Nevertheless, maybe a separate component is in fact the cleaner and recommended solution, so what do you think about this? 

# Any risks?

As far as i know, the mixins don't interfere with each other. However, based on the mixin names it might be a bit irritating to have both `RiverpodGameMixin` and `RiverpodComponentMixin` on one `FlameGame` class, but as `FlameGame` also extends `Component`, i think this is justified.

# More information

I can write the PR if this is considered useful.

### PR DESCRIPTION
**Pull request by tibotix**
# Description

This PR allows `RiverpodGameMixin` and `RiverpodComponentMixin` to be a mixin on the same `FlameGame` class.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [-] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2971 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
@markvideon

**Comment by tibotix** [comment]
@spydon I think as it is now this PR does not allow RiverpodGameMixin and RiverpodComponentMixin on the same component, at least it will not work as expected. We will likely not even continue working on this, as it is better to change  RiverpodGameMixin to have all features RiverpodComponentMixin has (as discussed in #2971 ) . I can open a new PR for this or continue with this one

**Comment by spydon** [comment]
> @spydon I think as it is now this PR does not allow RiverpodGameMixin and RiverpodComponentMixin on the same component, at least it will not work as expected. We will likely not even continue working on this, as it is better to change  RiverpodGameMixin to have all features RiverpodComponentMixin has (as discussed in #2971 ) . I can open a new PR for this or continue with this one

Whatever is the most convenient for you :)

**Comment by tibotix** [comment]
I think i will open a new PR for the new implementation.

**Pull request closed without merging**
