### PR TITLE
fix: Updated PolygonComponent.containsPoint to account for concave polygons

### PR DESCRIPTION
**Pull request by davidjan3**
# Description

Previously, the `PolygonComponent.containsPoint()` and `.containsLocalPoint()` functions consisted of duplicate code that checked whether a given point lies within a convex polygon. They didn't function properly with concave polygons.

I created a new `_containsPoint()` function that is called from both functions to reduce redundancies. This new function uses a different approach to figure out whether a point lies within a polygon, which should also work for concave polygons, or even polygons with holes. The algorithm is vaguely explained within code comments, and is visualized in this post: https://stackoverflow.com/a/218081/5008997

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
Looks good after a quick look, how's the performance impact?

**Comment by davidjan3** [comment]
Just stress-tested the performance within my current project.
Calling `containsPoint(vertex)` for 4 vertices on 10,000 randomly generated polygons with 10-24 vertices each:
Old method avg: ~370ms
New method avg: ~530ms

So it takes about 43% longer on average.

However, by replacing 
```dart
final edge = getEdge(i, vertices: vertices);
```
with
```dart
final from = vertices[i];
final to = vertices[(i + 1) % vertices.length];
``` 

It goes down to ~350ms and still survives every test. 
Though this also speeds up the old version to ~320ms.

It's important to note that in my test, the old function returns false almost all the time. And looking at the code, returning false can happen much faster than checking all edges before returning true.

**Comment by spydon** [comment]
@davidjan3 can you try with a bit more vertices, like 10?

**Comment by davidjan3** [comment]
All polygons had 10-24 vertices. My test just ran the `.containsPoint(vertex)` method 4 times per polygon, to see if all 4 corners of a rectangle lie within it. I can share my code sample after work.

**Comment by spydon** [comment]
> Otherwise I'd just add a couple tests and hope for approval.

Sounds good, seems like a reasonable performance trade-off.

**Comment by davidjan3** [comment]
@spydon So would you prefer keeping the `getEdge()` function for consistency, or should I push this?:


> However, by replacing
> 
> ```dart
> final edge = getEdge(i, vertices: vertices);
> ```
> 
> with
> 
> ```dart
> final from = vertices[i];
> final to = vertices[(i + 1) % vertices.length];
> ```
> 
> It goes down to ~350ms and still survives every test.

**Comment by spydon** [comment]
@davidjan3 sounds like it's definitely worth changing it then! :)

**Comment by davidjan3** [comment]
@spydon Added said optimization, and a little test :)

**Review by spydon — APPROVED** [review]
Lgtm! Sorry for the delay, I've been away skiing in the alps the last week :sweat_smile:

**Pull request merged**
