### PR TITLE
chore: Example game - added support for more platforms

### LINKED ISSUE #2670: Adding Linux support for Example project
When running `Example` project on Linux I am getting an error that Linux support is currently not supported for this project.

# What could be improved

As suggested by the flutter debuger in the console there are simple instructions in [flutter site](https://docs.flutter.dev/platform-integration/desktop#add-desktop-support-to-an-existing-flutter-app) to add support for more platforms.
Just running the commend `flutter create --platforms=windows,macos,linux .` will do

# Why should this be improved

So that new users who try to run `Example` project will have more options.
Sometimes developing apps on desktop native is faster because of build time and grater performance.
And the change required for that is so small there is no reason not to do so. 

# Any risks?

Safe

# More information

 
Interested working on this pr

### PR DESCRIPTION
**Pull request by guyluz11**
# Description

Run `flutter create --platforms=windows,macos,linux .` on the example project so that it can run on Linux

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
The user is responsible for running the `create` command in our example apps, none of the include platform specific files (if there hasn't been any modifications done to them).

**Comment by guyluz11** [comment]
image

**Comment by spydon** [comment]
I'll close this PR with reference to the last comment.
It also doesn't contain the linux directory and only a .metadata file change, since the linux directory along with all the other platform specific directories are in the .gitignore file and they weren't force added for this PR.

Thanks for trying to improve Flame though!

**Comment by guyluz11** [comment]
#2670

**Pull request closed without merging**
