### PR TITLE
chore: Add dependabot file

### PR DESCRIPTION
**Pull request by renancaraujo**
# Description

The result of running [this](https://github.com/renancaraujo/dependabot_gen) on the flame repo.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by spydon** [comment]
Since the packages should be updated through common dependencies `melos.yaml` I don't think that we want this yet for Flutter/Dart packages, there are issues open about adding support to Renovate and Dependabot for updating the melos file.

Probably we also don't want automatic updating of the public packages dependencies since that will lower the amount of people that can use them?

**Comment by renancaraujo** [comment]
> Since the packages should be updated through common dependencies in melos.yaml I don't think that we want this yet for Flutter/Dart packages, there are issues open about adding support to Renovate and Dependabot for updating the melos file.

We can restrict updates to only external dependencies (not under `/packages`)

> Probably we also don't want automatic updating of the public packages dependencies since that will lower the amount of people that can use them?

Since we gitignore the lock files, we would only receive alerts of new versions that are not covered by our current constraints, encouraging us to update the uppen boundary of those constraints. 


> And also we've seen massive problems when updating the sphinx dependencies, so I think updating the packages should be a conscious choice and non-automated.

Yikes, lets ignore sphinx then

**Comment by spydon** [comment]
> We can restrict updates to only external dependencies (not under /packages)

Sounds good :)

**Comment by renancaraujo** [comment]
now closing for reals cause melos people hates dependabot

**Pull request closed without merging**
