### PR TITLE
feat!: Flip gravity in flame_forge2d to be able to mix Forge2D and Flame components

### LINKED ISSUE #1132: Events on `PositionComponent` doesn't work in `flame_forge2d` for non-hud components
# Current bug behaviour
When adding a `PositionComponent` that has `isHud = false` (default) directly to a `Forge2DGame`, events aren't received since the coordinate system is flipped and `containsPoint` is looking at the flipped coordinates, which is not the coordinates that the component is rendered with.

# Expected behaviour
That `Draggable`, `Tappable` etc should work on `PositionComponent`s added directly to a `Forge2DGame`.

# Steps to reproduce
Create a non-hud `PositionComponent` with for example `Draggable` and add it to a `Forge2DGame` that has `HasDraggables`.

# More environment information

Create a list of more environment information, like:
* Flame version: 1.0.0-releasecandidate.16
* Forge2D version: 0.8.1
* flame_forge2d version: 0.8.2-releasecandidate.15
* Platform affected: android, ios, web
* Platform version affected: android 9, ios 13

# Workaround
Override `absoluteToLocal` in your `PositionComponent`:
```dart
  @override
  Vector2 absoluteToLocal(Vector2 point) {
    return super.absoluteToLocal(point..y *= -1);
  }
  ```

### LINKED ISSUE #1395: [flame_forge2d] Moving a component captured by the camera will cause that component to be displaced.
# Current bug behaviour
My `camera.followComponent(_player.positionComponent);` centres a component, but the component is somehow offset due to the velocity.

I have created a short GIF: 
Without debugMode

And a GIF with `debugMode` enabled. 
With debugMode

# Expected behaviour
The character sprite should always stays in the centre of the rectangle while moving.

# Steps to reproduce
I've made a minimal runnable example.
Clone it, "pug get" it and run it on your desired device.
https://bitbucket.org/Jinairu/minimalmovementexample/src/master/

# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95
    darwin-x64, locale en-DE)
    • Flutter version 2.8.1 at
      /Users/k.laabs/Documents/FlutterProjekte/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16
      08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0-rc5)
    • Android SDK at /Users/k.laabs/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is
      necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform
        side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#ins
      tallation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome
      98.0.4758.102```

# More environment information

* flame: 1.0.0
* flame_forge2d: ^0.8.3
* Platform affected: android, web

### LINKED ISSUE #1402: In a Forge2DGame, camera world coordinates differ from rendered objects' world coordinates.
The rendering code in flame_forge2d BodyComponent flips the y sign so that bodies render correctly.  But the Forge2DCamera also flips the y sign in it's projection methods.  The result is that a camera with camera.position of (-10,-10) is above the world x axis, and shows a forge2d body positioned at world coordinate (0, -10) as located below the x axis.  It is confusing to people such as myself trying to spin up on the project by plotting some simple Forge2D bodies.

### LINKED ISSUE #1484: FlameForge2d wrong position on PositionComponents.
# Current bug behaviour
When adding a position component to a Forge2D Game it is not rendered at the expected place, even when using `screenToWorld` or `worldToScreen`

# Expected behaviour
Position components should be rendered on the expected place

# Steps to reproduce
Use the following code:

```dart
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame_forge2d/body_component.dart';
import 'package:flame_forge2d/flame_forge2d.dart';
import 'package:flame_forge2d/forge2d_game.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(GameWidget(game: MyAwesomeGame()));
}

final position = Vector2(10, 10);

class CircleBody extends BodyComponent {
  @override
  Body createBody() {
    paint = Paint()..color = Colors.yellow;
    final def = BodyDef()
      ..type = BodyType.static
      ..position = position.clone();

    return world.createBody(def)
      ..createFixtureFromShape(CircleShape()..radius = 2);
  }
}

class MyAwesomeGame extends Forge2DGame {
  @override
  Future<void> onLoad() async {
    await super.onLoad();

    camera.followVector2(Vector2.zero());

    add(CircleBody());
    add(
      CircleComponent(
        radius: 2,
        position: screenToWorld(position.clone()),
        anchor: Anchor.center,
        paint: Paint()..color = Colors.pink,
      )
      //..flipVertically()
      //..flipHorizontally()
      //..flipVerticallyAroundCenter()
      //..flipHorizontallyAroundCenter(),
    );
  }
}
```

# More information

### PR DESCRIPTION
**Pull request by spydon**
# Description

Since the coordinate system in Forge2D is flipped we have had a lot of problems mixing Flame and Forge2D components in a `Forge2DGame`, but with this change the gravity of the Y-axis is flipped so a gravity of `Vector2(10, 0)` would pull your bodies downwards instead of upwards as it was previously.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

## Breaking Change

Since it flips the gravity this is a breaking change.

- [x] Yes, this is a breaking change.

## Related Issues

Closes #1484 
Closes #1402
Closes #1132 
Closes #1395

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
> @spydon if this is a breaking change what has to be modified from the developer's point of view?

This is still a draft, it depends on the final solution.

**Comment by st-pasha** [comment]
@spydon Can you, please, describe the current architecture to account for the "upside-down" Y axis, and whether this PR changes that architecture? I don't see the big picture here.

**Review by erickzanardo — APPROVED** [review]
LGTM

This seems appropriable xD: https://youtu.be/Iy2BcY0Drws?t=70

**Review by wolfenrain — APPROVED** [review]
LGTM! Only thing I noticed was that in some examples you also inverted some vertices (which makes sense), might be worth adding that to the docs as well? As that also deviates from Box2D right?

**Comment by spydon** [comment]
> LGTM! Only thing I noticed was that in some examples you also inverted some vertices (which makes sense), might be worth adding that to the docs as well? As that also deviates from Box2D right?

Fixed!

**Pull request merged**
