### PR TITLE
feat: Hexagonal maps

### LINKED ISSUE #1887: Hexagonal Support in `flame_tiled`
# What could be improved
Support Tiled's Hexagonal maps

image

# Why should this be improved
Gota have that Catan  hexagonal feel.

# Any risks?
Doesn't seem like it at first glance; but **I'm not an expert**. I didn't look into the painted layer. I didn't try to render objects from the object layer.

# More information

Building on #1882 and #1885 - I just wanted to go for completeness.  Hexagons was a bit more though since staggering between X/Y oriented tiles requires some juggling.  The other problem: hexagonal tiles are not square - if your destination tile size in `TiledComponent.load`  is wrong, it looks bad (gaps).

Possibly future improvement: discover the `destTileSize` automatically from the tmx files?

### PR DESCRIPTION
**Pull request by jtmcdole**
# Description

Adds support for Tiled's Hexagonal maps.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1887
Similar to #1882

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Nice, good job! What angle are the hexagonal tiles in when they are angled? Looks like less than for the isometric view?

**Comment by jtmcdole** [comment]
> What angle are the hexagonal tiles in when they are angled

I don't know for these specific tiles, but they are not top-down.  This is OK since Tiled doesn't ask you to define "length of one side" and force you into top-down mode - it asks you for tile width and height. I think this will work for trimetric hexagons (where width = 2 *h of the tile).  I can experiment later today or tomorrow.

**Review by erickzanardo — APPROVED** [review]

**Comment by kurtome** [comment]
@jtmcdole It looks like this PR inadvertently removed taking `layer.offsetX` and `layer.offsetY` into account when calculating the tile positions for renderable tile layers. I'm just going to add the offset as a `canvas.translate(offsetX, offsetY)` in the `render` function for that layer as part of #1886, does that sound right to you?

**Comment by jtmcdole** [comment]
@kurtome - it was in the previous PR. Sorry about that oversite!

When you do, can we add some golden tests to make sure this doesn't happen again? I added several goldens already, so it should be easy to add more.

**Pull request merged**
