### PR TITLE
tests: Clean up Component tests

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

Going through some of the component-related tests and performing general cleanup:
- Making sure the tests are in proper files (e.g. if a test tests the position of a PositionComponent, then it should be in the `position_component_test.dart` file);
- Use `testWithFlameGame` / `testWithGame` where appropriate;
- Some test names / variables names renamed for clarity;
- Make sure the `main()` function is at the top of the test file;
- Added test groups where it seemed to make sense;
- etc.

No tests were deleted or altered in any significant way (except when a test was a clear duplicate of another one).

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples`.

## Breaking Change

- [-] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

WIP for #1351

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Nice clean-up!

**Comment by spydon** [comment]
This should have the tests conventional commit tag, changing it.

**Comment by st-pasha** [comment]
Hmm, should it be "tests:" or "test:"? Is there a whitelist of prefixes that are allowed?

**Comment by spydon** [comment]
> Hmm, should it be "tests:" or "test:"? Is there a whitelist of prefixes that are allowed?

True, should have been `test:`, confusing that it is docs, but not tests. The "whitelist" is at https://www.conventionalcommits.org/en/v1.0.0/#summary but it's not really a proper list, I guess you could look in the GitHub action code too.

**Comment by st-pasha** [comment]
I've added the list to my #1897 PR.

**Pull request merged**
