### PR TITLE
[WIP] TiledComponent makes use of the SpriteBatch API

### PR DESCRIPTION
**Pull request by wolfenrain**
# Description
The current `TiledComponent` draws each tile individually on the canvas, switching to the `SpriteBatch` API will give a enormous performance gain because it will only do a single call to the canvas drawing all tiles using a single atlas.

**Note 1**: Because of how I implemented it, a developer wont be able to toggle the visibility of a layer. Because all the tiles are added to the `SpriteBatch` on creation, instead of drawn each frame, where the visibility check originally was.

**Note 2**: I also updated the constructor to accept a optional `Size` parameter for the destination instead of a required `double`. I made it optional so that it will grab the default tile size if non was given and so a developer could easily use irregular shaped tiles, which Tiled it self supports. But this has the side effect that the scaling wont properly work with irregular shaped tiles. But this will also be the case using a required `double` destination that does not fit with either the `width` or `height` depending on which value we use to calculate the scale.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [ ] I have made corresponding changes to the documentation
- [ ] I have added examples for new features in `doc/examples`
- [ ] The continuous integration (CI) is passing

### CODE REVIEW

**Comment by wolfenrain** [comment]
> LGTM. Nice! A next improvement we could make is to use the new Layer API to optionally pre-render maps. I do that with all our maps in our games, because it's too expensive for big maps to render every frame.

That would be a good optimization indeed, did you also check out the notes I added to the description? Might be blocking for merging(and the reason I put the PR on draft)

**Comment by erickzanardo** [comment]
About the first note, couldn't we just have a method that recreated the SpriteBatch so the visibility is check again?

The second note, if I understood correctly, the behaviour is the same as we have today right? So I don't see any problems.

**Comment by wolfenrain** [comment]
> About the first note, couldn't we just have a method that recreated the SpriteBatch so the visibility is check again?
> 
> The second note, if I understood correctly, the behaviour is the same as we have today right? So I don't see any problems.

Hmm that would be indeed a solution, a sort of `recreate` method. I could add it to this PR.

For the second note, yes it is technically the same outcome, but the point I was trying to make, which I should have formatted beter, is that the `destination size` parameter is useless when you want to scale down irregular shaped tiles. But it also messes up your x positions or y positions, if you scale it down on either the width of height of the given destination size, then the tiles wont align up, on either the x or y axis.

That is because the SpriteBatch applies the scale after applying the transform I believe? So even if you pre-scale your positions so it would fit, it would still not align I believe? But I am currently not a 100% sure if I tested that properly....

**Comment by wolfenrain** [comment]
I have finally gotten around to add a `generate` method so developers can generate the batches after messing with the visibility and such of each layer.

I have decided to keep the Size for the dstTileSize in, currently scaling does not work on both axis. But I do think it will be possible using transforms and such. But no clue on how to properly implement it right now. So I think it is ready for review.

**Comment by erickzanardo** [comment]
@wolfenrain we are moving the tiled features to a separe package: https://github.com/flame-engine/flame/pull/430

If it is not much to ask, would you mind move this PR to that repository after we merge the initial PR that is open there?

**Comment by wolfenrain** [comment]
Ofcourse. Just give me a pling either here or on discord and I will get right on it :+1:

**Comment by erickzanardo** [comment]
> Ofcourse. Just give me a pling either here or on discord and I will get right on it 👍

Awesome!! Thanks!

**Comment by erickzanardo** [comment]
@wolfenrain , when you get some time, here is the repository: https://github.com/flame-engine/flame_tiled

**Pull request closed without merging**
