### PR TITLE
Moving tiled support to a separate package

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Move tiled to a separate package, solving the issue we are having with the stable channel of Flutter.

We need this: https://github.com/flame-engine/flame_tiled/pull/1 and published merged before merging this

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
~- [ ] I have added examples for new features in `doc/examples`~
- [ ] The continuous integration (CI) is passing

### CODE REVIEW

**Comment by luanpotter** [comment]
Should this go to v1 branch?

**Comment by erickzanardo** [comment]
> Should this go to v1 branch?

Haven't we decided this to go on 0.25.0 because of the tiled issues with current Flutter stable branch?

**Comment by luanpotter** [comment]
Oh, I see. LGTM them but please make sure to merge, deploy & release a version of the new lib before merging this.

**Comment by erickzanardo** [comment]
> Oh, I see. LGTM them but please make sure to merge, deploy & release a version of the new lib before merging this.

Yep, I have mentioned that on the description of this pr...

**Pull request merged**
