### PR TITLE
feat: Added computed property CameraComponent.visibleWorldRect

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

The new property `camera.visibleWorldRect` gives the Aabb of the world region visible through the camera. This can be useful for culling the render pipeline, or similar purposes.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by st-pasha** [comment]
Not sure whether it's better to have it as `Aabb2` or as a `Rect`.

**Comment by wolfenrain** [comment]
Awesome stuff! I'll test this out tomorrow, I have a good usecase for this on the Sashimi engine that I made.

**Comment by spydon** [comment]
> Not sure whether it's better to have it as `Aabb2` or as a `Rect`.

The `Aabb2` is a bit easier to work with, except when you have to compare with a `Rect`, which we get from the `PositionComponent`s currently, so maybe we should have it as a `Rect` for now and then convert both for v2, if we feel the need for it?

**Review by spydon — APPROVED** [review]

**Review by erickzanardo — APPROVED** [review]

**Review by wolfenrain — APPROVED** [review]
Tested it in Sashimi and it is working like a charm, efficient as well!

**Pull request merged**
