### PR TITLE
Add lineHeight property to TextConfig

### PR DESCRIPTION
**Pull request by daisy1754**
# Description

Add lineHeight property to textConfig (pass through to https://api.flutter.dev/flutter/painting/TextStyle/height.html) so people can specify lineHeight. 

Example:
without property
Screen Shot 2020-10-18 at 1 44 13 PM

with property with value 1.5
Screen Shot 2020-10-18 at 1 44 31 PM

Fixes # (issue number, if there is one)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
- [ ] I have added examples for new features in `doc/examples`
- [ ] The continuous integration (CI) is passing

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm, seems like a useful thing to be able to specify

**Comment by spydon** [comment]
@erickzanardo didn't we fix the CI problem? It doesn't seem like it ran on this PR.

**Comment by erickzanardo** [comment]
> @erickzanardo didn't we fix the CI problem? It doesn't seem like it ran on this PR.

I probably forgot to bring the master to the develop branch :/

**Review by erickzanardo — APPROVED** [review]
LGTM

**Comment by daisy1754** [comment]
@spydon @erickzanardo will either of your merge this PR? It seems I don't have that permission

**Pull request merged**
