### PR TITLE
docs: Added contributors list

### PR DESCRIPTION
**Pull request by atulyakhatri**
# Description

- There were no contributors shown directly in the documentation
- Updated contributors list in the documentation : )
- This is a showcase
- It is not breaking anything!

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?
No

### Migration instructions

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by munsterlander** [comment]
Contributors are already shown. It's part of the default layout of github. Why duplicate it?  Furthermore, why use a third party tool that links to an outside source that could go offline?

**Comment by spydon** [comment]
We've already had a PR for this that has been closed, please search through the PRs before opening new ones. :)

**Comment by atulyakhatri** [comment]
###  Hey I only have tried to improve the documentation.

I thought it would look great but it didn't!
And I had not contributed for spamming purposes. If you don't like it, simply don't merge this. But don't label it as spam!

**And Thanks for your reviews and suggestions : )**

**Comment by spydon** [comment]
> ###  Hey I only have tried to improve the documentation.
> 
> I thought it would look great but it didn't!
> And I had not contributed for spamming purposes. If you don't like it, simply don't merge this. But don't label it as spam!
> 
> **And Thanks for your reviews and suggestions : )**

We had no issues posted for a change like this and we have already closed both an issue and PR regarding that change, so if you would have just done a quick search before you posted it you would have known it wouldn't be accepted and not have taken time from our already strained maintainers.

I also had a look at your profile and you had put up several PRs to repositories that clearly break the rules of Hacktoberfest (which has all been reported now) and also PRs that hadn't even read through the PRs template (which clearly stated that an issue should be created first), this made it even clearer to me that this deserved to get the spam label. My suggestion for you is that you read through the rules for the next years Hacktoberfest so that you can be an asset to the open source community, instead of a roadblock.

**Pull request closed without merging**
