### PR TITLE
fix: Adjust offset according to the Tiled Editor, Tileset Drawing Offset

### PR DESCRIPTION
**Pull request by Mythar**
# Description
Adjust offset according to the Tiled Editor, Tileset Drawing Offset

Tiled docs: https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tileset-properties

## Checklist

- [ ] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Replace or remove this text.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by spydon** [comment]
@Mythar you don't have to close the PR, it can continue to be updated. When you continue to push commits it is automatically updated.

**Comment by Mythar** [comment]
> @Mythar you don't have to close the PR, it can continue to be updated. When you continue to push commits it is automatically updated.

I had to make some changes to the code, and remove the *-1 on the offsetY.
Im not sure if this PR will use the new code?

**Comment by spydon** [comment]
@Mythar oops, I accidentally updated your comment instead of replying to it.

**Comment by Mythar** [comment]
> @Mythar oops, I accidentally updated your comment instead of replying to it.



> @Mythar oops, I accidentally updated your comment instead of replying to it.

LOL i saw ;)

**Comment by Mythar** [comment]
> So, you don't want to remove the files completely, you just want to revert the changes that were made to them. You start from the beginning by doing:
> 
> ```
> git reset --hard origin/main
> git push -f
> ```

I did not download the code to local, just did the changes in the browser.
Im on windows, and instructions are for linux

**Comment by spydon** [comment]
@Mythar you're going to need to have the code locally to be able to set up tests etc, you can also try the browser IDE (if you press `.` when you're in the PR). The instructions should work for any operating system that has `git` and `flutter` on the path.

**Comment by spydon** [comment]
I'll close this one @Mythar and then you can open another one if you decide to try again. :)

**Pull request closed without merging**
