### PR TITLE
feat: Expose atlas limits for `TiledComponent`

### LINKED ISSUE #2619: Strange overlapping issue with tilesets using flame_tiled
# Current bug behavior

There is a strange overlapping issue occurring at the time of rendering the map. I am using embedded tilesets and external as well. I have tried all the encodings(Base64, CSV), but still facing the same. The map is isometric with 256*128 tile size.
Screenshot 2023-07-24 at 11 10 40 AM

# Expected behavior

Screenshot 2023-07-24 at 11 11 30 AM

# Steps to reproduce

You will need to load isometric tilesets of 256*128 px size. Connect with me if you want the files.

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-IN)
    • Flutter version 3.10.6 on channel stable at
      /Users/ayaanpathan/Desktop/Development/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ayaanpathan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

# More environment information

Create a list of more environment information, like:
* Flame version: 1.8.0
* Flame tiled version: 1.12.0
* Platform affected: android, ios, web
* Platform version affected: tested on android 12, iOS 16 and web

# Log information

```
No errors
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/flame-engine) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/flame-engine/flame/issues/2619">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/flame-engine/flame/issues/2619/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description

This PR add the ability for users to override the max size of `TiledAtlas` used by `TiledComponent` for packing all the images of all the tilesets used by a tilemap. The overrides can be used if one is sure that their target platform can handle huge textures.

It also adds an assert for cases when the `RectangleBinPacker` runs out of space. This is done to help users find the problem quickly.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2619

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm! Maybe a short note about it in the docs? :)

**Comment by ufrshubham** [comment]
> Lgtm! Maybe a short note about it in the docs? :)

Sure, but I am a bit divided on where to put it. There are 2 places in the docs that talk about `TiledComponent`
- [Flame->Components->TiledComponent](https://docs.flame-engine.org/latest/flame/components.html#tiledcomponent)
- [Bridge Packages->flame_tiled](https://docs.flame-engine.org/latest/bridge_packages/flame_tiled/flame_tiled.html)

**Comment by spydon** [comment]
> > Lgtm! Maybe a short note about it in the docs? :)
> 
> Sure, but I am a bit divided on where to put it. There are 2 places in the docs that talk about `TiledComponent`
> 
>     * [Flame->Components->TiledComponent](https://docs.flame-engine.org/latest/flame/components.html#tiledcomponent)
> 
>     * [Bridge Packages->flame_tiled](https://docs.flame-engine.org/latest/bridge_packages/flame_tiled/flame_tiled.html)

We should probably move all the `components/tiledcomponent` docs to the `flame_tiled` page, I think that is just left from before when there wasn't any bridge package section.

**Comment by ufrshubham** [comment]
> We should probably move all the `components/tiledcomponent` docs to the `flame_tiled` page, I think that is just left from before when there wasn't any bridge package section.

Done. Moved out the `TiledComponent` section to flame_tiled and added a section about `TileAtlas`.

**Review by spydon — APPROVED** [review]

**Pull request merged**
