### PR TITLE
chore: Make the pngs smaller

### PR DESCRIPTION
**Pull request by kevmoo**
`find . -iname '*.png' | xargs oxipng -o max --trip safe`

### CODE REVIEW

**Comment by spydon** [comment]
Nice, the golden files should not be edited like this though.

**Comment by spydon** [comment]
I wonder why the golden tests fail though, since this is supposed to be a lossless operation :thinking:

**Comment by kevmoo** [comment]
Tried just going w/ the doc, example, media directories

**Review by spydon — APPROVED** [review]
Lgtm, thanks!

**Pull request merged**
